// vri-shaderc - offline Slang compiler, linked against the Slang compiler
// library (driven in-process via its C++ API). Compiles one .slang module (all
// of its [shader] entry points) into a single target blob and emits it as an
// embedded C header:
//   * --target spirv (default): a uint32 SPIR-V array (for Vulkan).
//   * --target wgsl: a WGSL string (for WebGPU). Slang emits WGSL directly, so
//     no SPIR-V->WGSL transpiler (naga/tint) is needed.
//   * --target dxbc|dxil: per-entry-point byte arrays for Direct3D 12. DXBC/DXIL
//     graphics shaders are single-entry (unlike a multi-entry SPIR-V module), so the
//     header gets one array per entry point, suffixed by stage: g_<var>VS, g_<var>PS,
//     g_<var>CS, ... (the D3D12 PSO takes one VS blob + one PS blob).
//
// Usage:
//   vri-shaderc <input.slang> -o <output.h> --var <g_name>
//               [--target spirv|wgsl|dxbc|dxil] [--profile <p>]
//
// This is the Phase-3 replacement for the temporary `xmake shaders` task that
// shelled out to the system slangc binary.

#include <slang.h>
#include <slang-com-ptr.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

using Slang::ComPtr;

namespace
{
    void PrintDiagnostics(slang::IBlob* diagnostics)
    {
        if (diagnostics && diagnostics->getBufferSize() > 0)
            std::fprintf(stderr, "%s\n", static_cast<const char*>(diagnostics->getBufferPointer()));
    }

    bool WriteHeader(const std::string& path, const std::string& varName, const uint32_t* words, size_t count)
    {
        std::ofstream f(path, std::ios::binary);
        if (!f)
            return false;
        f << "#pragma once\n";
        f << "// Generated by vri-shaderc (static-linked Slang). Do not edit by hand.\n";
        f << "#include <cstdint>\n";
        f << "const uint32_t " << varName << "[] = {\n";
        char buf[16];
        for (size_t i = 0; i < count; ++i)
        {
            std::snprintf(buf, sizeof(buf), "0x%08x,", words[i]);
            f << buf;
            if ((i % 8) == 7)
                f << '\n';
        }
        f << "\n};\n";
        return true;
    }

    // WGSL requires storage textures to declare an access mode, and Slang emits "read_write"
    // for every RWTexture. But WebGPU only permits read_write storage access on the r32*
    // formats; rgba8unorm and the rest must be "write" (or "read"). When a storage texture is
    // only written (no textureLoad of it anywhere), narrow it to "write" so the common
    // write-only compute pattern is valid on WebGPU. Genuinely read-write textures (a
    // textureLoad exists) are left untouched, and will simply require an r32* format.
    std::string NarrowWriteOnlyStorageTextures(std::string src)
    {
        const std::string marker = "texture_storage_";
        const std::string rwTok = ", read_write>";
        size_t scan = 0;
        while (true)
        {
            const size_t m = src.find(marker, scan);
            if (m == std::string::npos)
                break;
            const size_t close = src.find('>', m);
            if (close == std::string::npos)
                break;
            const size_t rw = src.rfind(rwTok, close);
            if (rw == std::string::npos || rw < m) // this declaration isn't read_write
            {
                scan = close + 1;
                continue;
            }
            // Recover the variable name: "var <name> : texture_storage_..."
            std::string name;
            const size_t varKw = src.rfind("var ", m);
            if (varKw != std::string::npos)
            {
                const size_t ns = varKw + 4;
                const size_t ne = src.find_first_of(" :", ns);
                if (ne != std::string::npos && ne <= m)
                    name = src.substr(ns, ne - ns);
            }
            const bool isRead = !name.empty() && src.find("textureLoad(" + name) != std::string::npos;
            if (!isRead)
            {
                src.replace(rw, rwTok.size(), ", write>");
                scan = rw + std::string(", write>").size();
            }
            else
            {
                scan = close + 1;
            }
        }
        return src;
    }

    // WGSL textureSampleCompare(Level) requires a texture_depth_* bound to a sampler_comparison,
    // but Slang emits an HLSL `Texture2D<float>` sampled via SampleCmp as `texture_2d<f32>`, which
    // makes the call ill-typed (it would return vec4 instead of f32). Find every texture used as
    // the first argument of a comparison sample and rewrite its declaration to texture_depth_2d.
    std::string DepthTexturesForComparison(std::string src)
    {
        auto isIdent = [](char c) { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'; };
        std::vector<std::string> names;
        for (const std::string& fn : {std::string("textureSampleCompareLevel("), std::string("textureSampleCompare(")})
        {
            size_t scan = 0;
            while (true)
            {
                const size_t c = src.find(fn, scan);
                if (c == std::string::npos) break;
                size_t a = c + fn.size();
                while (a < src.size() && (src[a] == '(' || src[a] == ' ')) ++a; // skip "((" / spaces
                size_t e = a;
                while (e < src.size() && isIdent(src[e])) ++e;
                if (e > a) names.push_back(src.substr(a, e - a));
                scan = c + fn.size();
            }
        }
        for (const std::string& n : names)
        {
            const std::string decl = "var " + n + " : texture_2d<f32>";
            const size_t d = src.find(decl);
            if (d != std::string::npos)
                src.replace(d, decl.size(), "var " + n + " : texture_depth_2d");
        }
        return src;
    }

    bool WriteTextHeader(const std::string& path, const std::string& varName, const char* text, size_t len)
    {
        while (len > 0 && text[len - 1] == '\0')
            --len; // drop trailing NUL(s)
        std::ofstream f(path, std::ios::binary);
        if (!f)
            return false;
        f << "#pragma once\n";
        f << "// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.\n";
        f << "inline const char " << varName << "[] = R\"VRIWGSL(\n";
        f.write(text, static_cast<std::streamsize>(len));
        f << "\n)VRIWGSL\";\n";
        return true;
    }

    const char* StageSuffix(SlangStage stage)
    {
        switch (stage)
        {
            case SLANG_STAGE_VERTEX:       return "VS";
            case SLANG_STAGE_FRAGMENT:     return "PS";
            case SLANG_STAGE_COMPUTE:      return "CS";
            case SLANG_STAGE_GEOMETRY:     return "GS";
            case SLANG_STAGE_HULL:         return "HS";
            case SLANG_STAGE_DOMAIN:       return "DS";
            case SLANG_STAGE_MESH:         return "MS";
            case SLANG_STAGE_AMPLIFICATION:return "AS";
            case SLANG_STAGE_RAY_GENERATION: return "RGEN";
            case SLANG_STAGE_MISS:         return "MISS";
            case SLANG_STAGE_CLOSEST_HIT:  return "CHIT";
            case SLANG_STAGE_ANY_HIT:      return "AHIT";
            case SLANG_STAGE_INTERSECTION: return "ISECT";
            case SLANG_STAGE_CALLABLE:     return "CALL";
            default:                       return "XX";
        }
    }

    // Append one entry-point byte blob as `inline const unsigned char <var>[] = {...};`.
    void AppendByteArray(std::ofstream& f, const std::string& varName, const unsigned char* bytes, size_t count)
    {
        f << "inline const unsigned char " << varName << "[] = {\n";
        char buf[8];
        for (size_t i = 0; i < count; ++i)
        {
            std::snprintf(buf, sizeof(buf), "0x%02x,", bytes[i]);
            f << buf;
            if ((i % 16) == 15)
                f << '\n';
        }
        f << "\n};\n";
    }

    // Split a path into directory + module stem (filename without ".slang").
    void SplitPath(const std::string& input, std::string& dir, std::string& stem)
    {
        const size_t slash = input.find_last_of("/\\");
        dir = slash == std::string::npos ? "." : input.substr(0, slash);
        std::string file = slash == std::string::npos ? input : input.substr(slash + 1);
        const size_t dot = file.find_last_of('.');
        stem = dot == std::string::npos ? file : file.substr(0, dot);
    }
} // namespace

int main(int argc, char** argv)
{
    std::string input, output, varName, profileName, targetName = "spirv";
    for (int i = 1; i < argc; ++i)
    {
        std::string a = argv[i];
        if (a == "-o" && i + 1 < argc)
            output = argv[++i];
        else if (a == "--var" && i + 1 < argc)
            varName = argv[++i];
        else if (a == "--profile" && i + 1 < argc)
            profileName = argv[++i];
        else if (a == "--target" && i + 1 < argc)
            targetName = argv[++i];
        else if (!a.empty() && a[0] != '-')
            input = a;
    }

    if (input.empty() || output.empty() || varName.empty())
    {
        std::fprintf(stderr, "usage: vri-shaderc <input.slang> -o <output.h> --var <g_name> [--target spirv|wgsl|dxbc|dxil] [--profile <p>]\n");
        return 2;
    }

    const bool wgsl = (targetName == "wgsl");
    const bool dxbc = (targetName == "dxbc");
    const bool dxil = (targetName == "dxil");
    const bool d3d = dxbc || dxil; // per-entry-point byte blobs
    if (!wgsl && !d3d && targetName != "spirv")
    {
        std::fprintf(stderr, "vri-shaderc: unknown --target '%s' (expected spirv|wgsl|dxbc|dxil)\n", targetName.c_str());
        return 2;
    }
    if (profileName.empty()) // sensible default profile per target
        profileName = dxbc ? "sm_5_1" : (dxil ? "sm_6_0" : "spirv_1_5");

    std::string dir, stem;
    SplitPath(input, dir, stem);

    ComPtr<slang::IGlobalSession> global;
    if (SLANG_FAILED(slang::createGlobalSession(global.writeRef())))
    {
        std::fprintf(stderr, "vri-shaderc: failed to create Slang global session\n");
        return 1;
    }

    slang::TargetDesc target = {};
    target.format = wgsl ? SLANG_WGSL : (dxbc ? SLANG_DXBC : (dxil ? SLANG_DXIL : SLANG_SPIRV));
    if (!wgsl)
        target.profile = global->findProfile(profileName.c_str());

    slang::CompilerOptionEntry options[2] = {};
    // Preserve original entry-point names in SPIR-V (don't rename to "main"),
    // so a single multi-entry module can be referenced by name per stage.
    options[0].name = slang::CompilerOptionName::VulkanUseEntryPointName;
    options[0].value.kind = slang::CompilerOptionValueKind::Int;
    options[0].value.intValue0 = 1;
    // Use Slang's native SPIR-V backend instead of the glslang+spirv-opt
    // downstream, so the tool needs no extra DLLs (slang-glslang / spirv-opt).
    options[1].name = slang::CompilerOptionName::EmitSpirvDirectly;
    options[1].value.kind = slang::CompilerOptionValueKind::Int;
    options[1].value.intValue0 = 1;

    const char* searchPaths[] = {dir.c_str()};

    slang::SessionDesc sessionDesc = {};
    sessionDesc.targets = &target;
    sessionDesc.targetCount = 1;
    sessionDesc.searchPaths = searchPaths;
    sessionDesc.searchPathCount = 1;
    sessionDesc.compilerOptionEntries = options;
    sessionDesc.compilerOptionEntryCount = d3d ? 0 : (wgsl ? 1 : 2); // SPIR-V-only options

    ComPtr<slang::ISession> session;
    if (SLANG_FAILED(global->createSession(sessionDesc, session.writeRef())))
    {
        std::fprintf(stderr, "vri-shaderc: failed to create Slang session\n");
        return 1;
    }

    ComPtr<slang::IBlob> diagnostics;
    slang::IModule* module = session->loadModule(stem.c_str(), diagnostics.writeRef());
    PrintDiagnostics(diagnostics);
    if (!module)
    {
        std::fprintf(stderr, "vri-shaderc: failed to load module '%s'\n", input.c_str());
        return 1;
    }

    // module + all of its defined entry points -> one composite component.
    std::vector<slang::IComponentType*> components;
    components.push_back(module);
    std::vector<ComPtr<slang::IEntryPoint>> entryPoints;
    const SlangInt32 epCount = module->getDefinedEntryPointCount();
    for (SlangInt32 i = 0; i < epCount; ++i)
    {
        ComPtr<slang::IEntryPoint> ep;
        if (SLANG_FAILED(module->getDefinedEntryPoint(i, ep.writeRef())))
            continue;
        entryPoints.push_back(ep);
        components.push_back(ep.get());
    }
    if (entryPoints.empty())
    {
        std::fprintf(stderr, "vri-shaderc: no [shader] entry points found in '%s'\n", input.c_str());
        return 1;
    }

    ComPtr<slang::IComponentType> composed;
    {
        ComPtr<slang::IBlob> d;
        SlangResult r = session->createCompositeComponentType(
            components.data(), static_cast<SlangInt>(components.size()), composed.writeRef(), d.writeRef());
        PrintDiagnostics(d);
        if (SLANG_FAILED(r))
            return 1;
    }

    ComPtr<slang::IComponentType> linked;
    {
        ComPtr<slang::IBlob> d;
        SlangResult r = composed->link(linked.writeRef(), d.writeRef());
        PrintDiagnostics(d);
        if (SLANG_FAILED(r))
            return 1;
    }

    // D3D (DXBC/DXIL): one byte blob per entry point, suffixed by stage. The header
    // holds e.g. g_<var>VS + g_<var>PS, since a graphics PSO takes a VS blob + PS blob.
    if (d3d)
    {
        slang::ProgramLayout* layout = linked->getLayout(0, nullptr);
        if (!layout) { std::fprintf(stderr, "vri-shaderc: no program layout\n"); return 1; }
        std::ofstream f(output, std::ios::binary);
        if (!f) { std::fprintf(stderr, "vri-shaderc: failed to write '%s'\n", output.c_str()); return 1; }
        f << "#pragma once\n";
        f << "// Generated by vri-shaderc (Slang -> " << (dxil ? "DXIL" : "DXBC") << "). Do not edit by hand.\n";
        const unsigned epc = static_cast<unsigned>(layout->getEntryPointCount());
        size_t totalBytes = 0;
        for (unsigned i = 0; i < epc; ++i)
        {
            slang::EntryPointReflection* er = layout->getEntryPointByIndex(i);
            const char* suffix = StageSuffix(er->getStage());
            ComPtr<slang::IBlob> ep;
            ComPtr<slang::IBlob> d;
            SlangResult r = linked->getEntryPointCode(static_cast<SlangInt>(i), 0, ep.writeRef(), d.writeRef());
            PrintDiagnostics(d);
            if (SLANG_FAILED(r)) return 1;
            AppendByteArray(f, varName + suffix, static_cast<const unsigned char*>(ep->getBufferPointer()), ep->getBufferSize());
            totalBytes += ep->getBufferSize();
        }
        std::printf("vri-shaderc: %s -> %s (%s, %s, %u entry points, %zu bytes)\n",
                    input.c_str(), output.c_str(), varName.c_str(), targetName.c_str(), epc, totalBytes);
        return 0;
    }

    ComPtr<slang::IBlob> code;
    {
        ComPtr<slang::IBlob> d;
        SlangResult r = linked->getTargetCode(0, code.writeRef(), d.writeRef());
        PrintDiagnostics(d);
        if (SLANG_FAILED(r))
            return 1;
    }

    const size_t byteSize = code->getBufferSize();
    bool ok;
    if (wgsl)
    {
        std::string wgslSrc = NarrowWriteOnlyStorageTextures(
            std::string(static_cast<const char*>(code->getBufferPointer()), byteSize));
        wgslSrc = DepthTexturesForComparison(std::move(wgslSrc));
        ok = WriteTextHeader(output, varName, wgslSrc.c_str(), wgslSrc.size());
    }
    else
    {
        if (byteSize % 4 != 0)
        {
            std::fprintf(stderr, "vri-shaderc: SPIR-V size not a multiple of 4\n");
            return 1;
        }
        ok = WriteHeader(output, varName, static_cast<const uint32_t*>(code->getBufferPointer()), byteSize / 4);
    }
    if (!ok)
    {
        std::fprintf(stderr, "vri-shaderc: failed to write '%s'\n", output.c_str());
        return 1;
    }

    std::printf("vri-shaderc: %s -> %s (%s, %s, %zu entry points, %zu bytes)\n",
                input.c_str(), output.c_str(), varName.c_str(), targetName.c_str(), entryPoints.size(), byteSize);
    return 0;
}
