#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_cubeWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Camera_std140_0
{
    @align(16) mvp_0 : _MatrixStorage_float4x4std140_0,
};

@binding(0) @group(0) var<uniform> uCam_0 : Camera_std140_0;
@binding(1) @group(0) var uTex_0 : texture_2d<f32>;

@binding(2) @group(0) var uSmp_0 : sampler;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) uv_1 : vec2<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(_S1.position_1, 1.0f)) * (mat4x4<f32>(uCam_0.mvp_0.data_0[i32(0)][i32(0)], uCam_0.mvp_0.data_0[i32(0)][i32(1)], uCam_0.mvp_0.data_0[i32(0)][i32(2)], uCam_0.mvp_0.data_0[i32(0)][i32(3)], uCam_0.mvp_0.data_0[i32(1)][i32(0)], uCam_0.mvp_0.data_0[i32(1)][i32(1)], uCam_0.mvp_0.data_0[i32(1)][i32(2)], uCam_0.mvp_0.data_0[i32(1)][i32(3)], uCam_0.mvp_0.data_0[i32(2)][i32(0)], uCam_0.mvp_0.data_0[i32(2)][i32(1)], uCam_0.mvp_0.data_0[i32(2)][i32(2)], uCam_0.mvp_0.data_0[i32(2)][i32(3)], uCam_0.mvp_0.data_0[i32(3)][i32(0)], uCam_0.mvp_0.data_0[i32(3)][i32(1)], uCam_0.mvp_0.data_0[i32(3)][i32(2)], uCam_0.mvp_0.data_0[i32(3)][i32(3)]))));
    o_0.uv_0 = _S1.uv_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_2 : vec2<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var _S3 : pixelOutput_0 = pixelOutput_0( (textureSample((uTex_0), (uSmp_0), (_S2.uv_2))) );
    return _S3;
}


)VRIWGSL";
