#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_borderQuadWgsl[] = R"VRIWGSL(
@binding(0) @group(0) var uTex_0 : texture_2d<f32>;

@binding(1) @group(0) var uSmp_0 : sampler;

const kCorners_0 : array<vec2<f32>, i32(6)> = array<vec2<f32>, i32(6)>( vec2<f32>(-0.85000002384185791f, -0.85000002384185791f), vec2<f32>(0.85000002384185791f, -0.85000002384185791f), vec2<f32>(-0.85000002384185791f, 0.85000002384185791f), vec2<f32>(0.85000002384185791f, -0.85000002384185791f), vec2<f32>(0.85000002384185791f, 0.85000002384185791f), vec2<f32>(-0.85000002384185791f, 0.85000002384185791f) );
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(kCorners_0[vid_0], 0.0f, 1.0f);
    var _S1 : vec2<f32> = vec2<f32>(0.5f);
    o_0.uv_0 = (kCorners_0[vid_0] / vec2<f32>(0.85000002384185791f) * _S1 + _S1) * vec2<f32>(3.0f) - vec2<f32>(1.0f);
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S3 : pixelOutput_0 = pixelOutput_0( (textureSample((uTex_0), (uSmp_0), (_S2.uv_1))) );
    return _S3;
}


)VRIWGSL";
