#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_computePlasmaWgsl[] = R"VRIWGSL(
struct Params_std140_0
{
    @align(16) time_0 : f32,
    @align(4) width_0 : u32,
    @align(8) height_0 : u32,
    @align(4) pad_0 : u32,
};

@binding(0) @group(0) var<uniform> uParams_0 : Params_std140_0;
@binding(1) @group(0) var uOut_0 : texture_storage_2d<rgba8unorm, write>;

fn Plasma_0( uv_0 : vec2<f32>,  t_0 : f32) -> vec3<f32>
{
    var _S1 : f32 = uv_0.x;
    var _S2 : f32 = uv_0.y;
    var _S3 : vec3<f32> = vec3<f32>(0.5f);
    return _S3 + _S3 * cos(vec3<f32>(0.0f, 2.0f, 4.0f) + vec3<f32>(((sin(_S1 * 10.0f + t_0) + sin(_S2 * 10.0f + t_0 * 1.29999995231628418f) + sin((_S1 + _S2) * 10.0f + t_0 * 0.69999998807907104f) + sin(length(uv_0 - vec2<f32>(0.5f)) * 16.0f - t_0 * 1.5f)) * 1.20000004768371582f)));
}

@compute
@workgroup_size(8, 8, 1)
fn computeMain(@builtin(global_invocation_id) id_0 : vec3<u32>)
{
    var _S4 : bool;
    if((id_0.x) >= (uParams_0.width_0))
    {
        _S4 = true;
    }
    else
    {
        _S4 = (id_0.y) >= (uParams_0.height_0);
    }
    if(_S4)
    {
        return;
    }
    var _S5 : vec2<u32> = id_0.xy;
    textureStore((uOut_0), (_S5), (vec4<f32>(Plasma_0((vec2<f32>(_S5) + vec2<f32>(0.5f)) / vec2<f32>(f32(uParams_0.width_0), f32(uParams_0.height_0)), uParams_0.time_0), 1.0f)));
    return;
}


)VRIWGSL";
