#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_consrastSceneWgsl[] = R"VRIWGSL(
struct Push_std430_0
{
    @align(16) rot_0 : vec4<f32>,
};

var<uniform> pc_0 : Push_std430_0;
const kColors_0 : array<vec3<f32>, i32(3)> = array<vec3<f32>, i32(3)>( vec3<f32>(1.0f, 0.34999999403953552f, 0.30000001192092896f), vec3<f32>(0.40000000596046448f, 1.0f, 0.5f), vec3<f32>(1.0f, 0.89999997615814209f, 0.30000001192092896f) );
const kPositions_0 : array<vec2<f32>, i32(9)> = array<vec2<f32>, i32(9)>( vec2<f32>(0.0f, 0.0f), vec2<f32>(0.92000001668930054f, 0.01200000010430813f), vec2<f32>(0.92000001668930054f, -0.01200000010430813f), vec2<f32>(0.0f, 0.0f), vec2<f32>(-0.44960001111030579f, 0.80279999971389771f), vec2<f32>(-0.47040000557899475f, 0.79079997539520264f), vec2<f32>(0.0f, 0.0f), vec2<f32>(-0.47040000557899475f, -0.79079997539520264f), vec2<f32>(-0.44960001111030579f, -0.80279999971389771f) );
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) color_0 : vec3<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var _S1 : f32 = kPositions_0[vid_0].x;
    var _S2 : f32 = kPositions_0[vid_0].y;
    var p_0 : vec2<f32> = vec2<f32>(_S1 * pc_0.rot_0.x - _S2 * pc_0.rot_0.y, _S1 * pc_0.rot_0.y + _S2 * pc_0.rot_0.x);
    p_0[i32(0)] = p_0[i32(0)] * pc_0.rot_0.z;
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_0, 0.0f, 1.0f);
    o_0.color_0 = kColors_0[vid_0 / u32(3)];
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) color_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S3 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S4 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S3.color_1, 1.0f) );
    return _S4;
}


)VRIWGSL";
