#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_deferredLightWgsl[] = R"VRIWGSL(
@binding(1) @group(0) var uPosition_0 : texture_2d<f32>;

@binding(4) @group(0) var uSmp_0 : sampler;

@binding(2) @group(0) var uNormal_0 : texture_2d<f32>;

@binding(3) @group(0) var uAlbedoSpec_0 : texture_2d<f32>;

struct Ubo_std140_0
{
    @align(16) lightPosition_0 : array<vec4<f32>, i32(6)>,
    @align(16) lightColor_0 : array<vec4<f32>, i32(6)>,
    @align(16) viewPos_0 : vec4<f32>,
    @align(16) params_0 : vec4<i32>,
};

@binding(0) @group(0) var<uniform> uUbo_0 : Ubo_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var _S1 : f32 = f32((((vid_0 << (u32(1)))) & (u32(2))));
    var _S2 : f32 = f32((vid_0 & (u32(2))));
    var p_0 : vec2<f32> = vec2<f32>(_S1, _S2);
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(_S1 * 2.0f - 1.0f, 1.0f - _S2 * 2.0f, 0.0f, 1.0f);
    o_0.uv_0 = p_0;
    return o_0;
}

fn shadeLight_0( lightPos_0 : vec4<f32>,  lightCol_0 : vec4<f32>,  fragPos_0 : vec3<f32>,  N_0 : vec3<f32>,  V_0 : vec3<f32>,  albedoSpec_0 : vec4<f32>) -> vec3<f32>
{
    var toLight_0 : vec3<f32> = lightPos_0.xyz - fragPos_0;
    var dist_0 : f32 = length(toLight_0);
    var L_0 : vec3<f32> = toLight_0 / vec3<f32>(max(dist_0, 0.00009999999747379f));
    var _S3 : vec3<f32> = lightCol_0.xyz;
    var _S4 : vec3<f32> = vec3<f32>((lightCol_0.w / (dist_0 * dist_0 + 1.0f)));
    return _S3 * albedoSpec_0.xyz * vec3<f32>(max(0.0f, dot(N_0, L_0))) * _S4 + _S3 * vec3<f32>(albedoSpec_0.w) * vec3<f32>(pow(max(0.0f, dot(reflect((vec3<f32>(0) - L_0), N_0), V_0)), 16.0f)) * _S4;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
};

@fragment
fn fragmentMain( _S5 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var fragPos_1 : vec3<f32> = (textureSample((uPosition_0), (uSmp_0), (_S5.uv_1))).xyz;
    var N_1 : vec3<f32> = normalize((textureSample((uNormal_0), (uSmp_0), (_S5.uv_1))).xyz * vec3<f32>(2.0f) - vec3<f32>(1.0f));
    var albedoSpec_1 : vec4<f32> = (textureSample((uAlbedoSpec_0), (uSmp_0), (_S5.uv_1)));
    var debug_0 : i32 = uUbo_0.params_0.x;
    if(debug_0 == i32(1))
    {
        var _S6 : pixelOutput_0 = pixelOutput_0( vec4<f32>(fragPos_1 * vec3<f32>(0.07999999821186066f) + vec3<f32>(0.5f), 1.0f) );
        return _S6;
    }
    if(debug_0 == i32(2))
    {
        var _S7 : vec3<f32> = vec3<f32>(0.5f);
        var _S8 : pixelOutput_0 = pixelOutput_0( vec4<f32>(N_1 * _S7 + _S7, 1.0f) );
        return _S8;
    }
    if(debug_0 == i32(3))
    {
        var _S9 : pixelOutput_0 = pixelOutput_0( vec4<f32>(albedoSpec_1.xyz, 1.0f) );
        return _S9;
    }
    if(debug_0 == i32(4))
    {
        var _S10 : pixelOutput_0 = pixelOutput_0( vec4<f32>(albedoSpec_1.www, 1.0f) );
        return _S10;
    }
    var V_1 : vec3<f32> = normalize(uUbo_0.viewPos_0.xyz - fragPos_1);
    var _S11 : pixelOutput_0 = pixelOutput_0( vec4<f32>(albedoSpec_1.xyz * vec3<f32>(0.10000000149011612f) + shadeLight_0(uUbo_0.lightPosition_0[i32(0)], uUbo_0.lightColor_0[i32(0)], fragPos_1, N_1, V_1, albedoSpec_1) + shadeLight_0(uUbo_0.lightPosition_0[i32(1)], uUbo_0.lightColor_0[i32(1)], fragPos_1, N_1, V_1, albedoSpec_1) + shadeLight_0(uUbo_0.lightPosition_0[i32(2)], uUbo_0.lightColor_0[i32(2)], fragPos_1, N_1, V_1, albedoSpec_1) + shadeLight_0(uUbo_0.lightPosition_0[i32(3)], uUbo_0.lightColor_0[i32(3)], fragPos_1, N_1, V_1, albedoSpec_1) + shadeLight_0(uUbo_0.lightPosition_0[i32(4)], uUbo_0.lightColor_0[i32(4)], fragPos_1, N_1, V_1, albedoSpec_1) + shadeLight_0(uUbo_0.lightPosition_0[i32(5)], uUbo_0.lightColor_0[i32(5)], fragPos_1, N_1, V_1, albedoSpec_1), 1.0f) );
    return _S11;
}


)VRIWGSL";
