#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_genPlasmaWgsl[] = R"VRIWGSL(
struct Params_std140_0
{
    @align(16) time_0 : f32,
    @align(4) width_0 : u32,
    @align(8) height_0 : u32,
    @align(4) pad_0 : u32,
};

@binding(0) @group(0) var<uniform> uParams_0 : Params_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var p_0 : vec2<f32> = vec2<f32>(f32((((vid_0 << (u32(1)))) & (u32(2)))), f32((vid_0 & (u32(2)))));
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_0 * vec2<f32>(2.0f) - vec2<f32>(1.0f), 0.0f, 1.0f);
    o_0.uv_0 = p_0;
    return o_0;
}

fn Plasma_0( uv_1 : vec2<f32>,  t_0 : f32) -> vec3<f32>
{
    var _S1 : f32 = uv_1.x;
    var _S2 : f32 = uv_1.y;
    var _S3 : vec3<f32> = vec3<f32>(0.5f);
    return _S3 + _S3 * cos(vec3<f32>(0.0f, 2.0f, 4.0f) + vec3<f32>(((sin(_S1 * 10.0f + t_0) + sin(_S2 * 10.0f + t_0 * 1.29999995231628418f) + sin((_S1 + _S2) * 10.0f + t_0 * 0.69999998807907104f) + sin(length(uv_1 - vec2<f32>(0.5f)) * 16.0f - t_0 * 1.5f)) * 1.20000004768371582f)));
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_2 : vec2<f32>,
};

@fragment
fn fragmentMain( _S4 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S5 : pixelOutput_0 = pixelOutput_0( vec4<f32>(Plasma_0(_S4.uv_2, uParams_0.time_0), 1.0f) );
    return _S5;
}


)VRIWGSL";
