#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_geomSceneWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Camera_std140_0
{
    @align(16) mvp_0 : _MatrixStorage_float4x4std140_0,
    @align(16) model_0 : _MatrixStorage_float4x4std140_0,
    @align(16) misc_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> uCam_0 : Camera_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldN_0 : vec3<f32>,
    @location(1) worldP_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) pos_0 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    var _S2 : vec4<f32> = vec4<f32>(_S1.pos_0, 1.0f);
    o_0.position_0 = (((_S2) * (mat4x4<f32>(uCam_0.mvp_0.data_0[i32(0)][i32(0)], uCam_0.mvp_0.data_0[i32(0)][i32(1)], uCam_0.mvp_0.data_0[i32(0)][i32(2)], uCam_0.mvp_0.data_0[i32(0)][i32(3)], uCam_0.mvp_0.data_0[i32(1)][i32(0)], uCam_0.mvp_0.data_0[i32(1)][i32(1)], uCam_0.mvp_0.data_0[i32(1)][i32(2)], uCam_0.mvp_0.data_0[i32(1)][i32(3)], uCam_0.mvp_0.data_0[i32(2)][i32(0)], uCam_0.mvp_0.data_0[i32(2)][i32(1)], uCam_0.mvp_0.data_0[i32(2)][i32(2)], uCam_0.mvp_0.data_0[i32(2)][i32(3)], uCam_0.mvp_0.data_0[i32(3)][i32(0)], uCam_0.mvp_0.data_0[i32(3)][i32(1)], uCam_0.mvp_0.data_0[i32(3)][i32(2)], uCam_0.mvp_0.data_0[i32(3)][i32(3)]))));
    o_0.worldN_0 = (((vec4<f32>(_S1.normal_0, 0.0f)) * (mat4x4<f32>(uCam_0.model_0.data_0[i32(0)][i32(0)], uCam_0.model_0.data_0[i32(0)][i32(1)], uCam_0.model_0.data_0[i32(0)][i32(2)], uCam_0.model_0.data_0[i32(0)][i32(3)], uCam_0.model_0.data_0[i32(1)][i32(0)], uCam_0.model_0.data_0[i32(1)][i32(1)], uCam_0.model_0.data_0[i32(1)][i32(2)], uCam_0.model_0.data_0[i32(1)][i32(3)], uCam_0.model_0.data_0[i32(2)][i32(0)], uCam_0.model_0.data_0[i32(2)][i32(1)], uCam_0.model_0.data_0[i32(2)][i32(2)], uCam_0.model_0.data_0[i32(2)][i32(3)], uCam_0.model_0.data_0[i32(3)][i32(0)], uCam_0.model_0.data_0[i32(3)][i32(1)], uCam_0.model_0.data_0[i32(3)][i32(2)], uCam_0.model_0.data_0[i32(3)][i32(3)])))).xyz;
    o_0.worldP_0 = (((_S2) * (mat4x4<f32>(uCam_0.model_0.data_0[i32(0)][i32(0)], uCam_0.model_0.data_0[i32(0)][i32(1)], uCam_0.model_0.data_0[i32(0)][i32(2)], uCam_0.model_0.data_0[i32(0)][i32(3)], uCam_0.model_0.data_0[i32(1)][i32(0)], uCam_0.model_0.data_0[i32(1)][i32(1)], uCam_0.model_0.data_0[i32(1)][i32(2)], uCam_0.model_0.data_0[i32(1)][i32(3)], uCam_0.model_0.data_0[i32(2)][i32(0)], uCam_0.model_0.data_0[i32(2)][i32(1)], uCam_0.model_0.data_0[i32(2)][i32(2)], uCam_0.model_0.data_0[i32(2)][i32(3)], uCam_0.model_0.data_0[i32(3)][i32(0)], uCam_0.model_0.data_0[i32(3)][i32(1)], uCam_0.model_0.data_0[i32(3)][i32(2)], uCam_0.model_0.data_0[i32(3)][i32(3)])))).xyz;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldN_1 : vec3<f32>,
    @location(1) worldP_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S3 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var lightDir_0 : vec3<f32> = normalize(vec3<f32>(0.44999998807907104f, 0.80000001192092896f, 0.44999998807907104f));
    var n_0 : vec3<f32> = normalize(_S3.worldN_1);
    var _S4 : pixelOutput_0 = pixelOutput_0( vec4<f32>(vec3<f32>(0.34999999403953552f, 0.5f, 0.85000002384185791f) * vec3<f32>((0.15000000596046448f + 0.85000002384185791f * max(dot(n_0, lightDir_0), 0.0f))) + vec3<f32>(0.89999997615814209f, 0.89999997615814209f, 1.0f) * vec3<f32>(pow(max(dot(n_0, normalize(lightDir_0 + normalize(vec3<f32>(0.0f, 0.60000002384185791f, 2.59999990463256836f) - _S3.worldP_1))), 0.0f), 48.0f)) * vec3<f32>(0.60000002384185791f), 1.0f) );
    return _S4;
}


)VRIWGSL";
