#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_msaaWgsl[] = R"VRIWGSL(
struct Push_std430_0
{
    @align(16) rot_0 : vec4<f32>,
};

var<uniform> pc_0 : Push_std430_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) color_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) pos_0 : vec2<f32>,
    @location(1) color_1 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var _S2 : f32 = _S1.pos_0.x;
    var _S3 : f32 = _S1.pos_0.y;
    var p_0 : vec2<f32> = vec2<f32>(_S2 * pc_0.rot_0.x - _S3 * pc_0.rot_0.y, _S2 * pc_0.rot_0.y + _S3 * pc_0.rot_0.x);
    p_0[i32(0)] = p_0[i32(0)] * pc_0.rot_0.z;
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_0, 0.0f, 1.0f);
    o_0.color_0 = _S1.color_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) color_2 : vec3<f32>,
};

@fragment
fn fragmentMain( _S4 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S5 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S4.color_2, 1.0f) );
    return _S5;
}


)VRIWGSL";
