#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_occlSceneWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Push_std430_0
{
    @align(16) model_0 : _MatrixStorage_float4x4std430_0,
    @align(16) color_0 : vec4<f32>,
};

var<uniform> pc_0 : Push_std430_0;
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_1 : array<vec4<f32>, i32(4)>,
};

struct Camera_std140_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4std140_0,
};

@binding(0) @group(0) var<uniform> uCam_0 : Camera_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldN_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) pos_0 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = ((((((vec4<f32>(_S1.pos_0, 1.0f)) * (mat4x4<f32>(pc_0.model_0.data_0[i32(0)][i32(0)], pc_0.model_0.data_0[i32(0)][i32(1)], pc_0.model_0.data_0[i32(0)][i32(2)], pc_0.model_0.data_0[i32(0)][i32(3)], pc_0.model_0.data_0[i32(1)][i32(0)], pc_0.model_0.data_0[i32(1)][i32(1)], pc_0.model_0.data_0[i32(1)][i32(2)], pc_0.model_0.data_0[i32(1)][i32(3)], pc_0.model_0.data_0[i32(2)][i32(0)], pc_0.model_0.data_0[i32(2)][i32(1)], pc_0.model_0.data_0[i32(2)][i32(2)], pc_0.model_0.data_0[i32(2)][i32(3)], pc_0.model_0.data_0[i32(3)][i32(0)], pc_0.model_0.data_0[i32(3)][i32(1)], pc_0.model_0.data_0[i32(3)][i32(2)], pc_0.model_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(uCam_0.viewProj_0.data_1[i32(0)][i32(0)], uCam_0.viewProj_0.data_1[i32(0)][i32(1)], uCam_0.viewProj_0.data_1[i32(0)][i32(2)], uCam_0.viewProj_0.data_1[i32(0)][i32(3)], uCam_0.viewProj_0.data_1[i32(1)][i32(0)], uCam_0.viewProj_0.data_1[i32(1)][i32(1)], uCam_0.viewProj_0.data_1[i32(1)][i32(2)], uCam_0.viewProj_0.data_1[i32(1)][i32(3)], uCam_0.viewProj_0.data_1[i32(2)][i32(0)], uCam_0.viewProj_0.data_1[i32(2)][i32(1)], uCam_0.viewProj_0.data_1[i32(2)][i32(2)], uCam_0.viewProj_0.data_1[i32(2)][i32(3)], uCam_0.viewProj_0.data_1[i32(3)][i32(0)], uCam_0.viewProj_0.data_1[i32(3)][i32(1)], uCam_0.viewProj_0.data_1[i32(3)][i32(2)], uCam_0.viewProj_0.data_1[i32(3)][i32(3)]))));
    o_0.worldN_0 = (((vec4<f32>(_S1.normal_0, 0.0f)) * (mat4x4<f32>(pc_0.model_0.data_0[i32(0)][i32(0)], pc_0.model_0.data_0[i32(0)][i32(1)], pc_0.model_0.data_0[i32(0)][i32(2)], pc_0.model_0.data_0[i32(0)][i32(3)], pc_0.model_0.data_0[i32(1)][i32(0)], pc_0.model_0.data_0[i32(1)][i32(1)], pc_0.model_0.data_0[i32(1)][i32(2)], pc_0.model_0.data_0[i32(1)][i32(3)], pc_0.model_0.data_0[i32(2)][i32(0)], pc_0.model_0.data_0[i32(2)][i32(1)], pc_0.model_0.data_0[i32(2)][i32(2)], pc_0.model_0.data_0[i32(2)][i32(3)], pc_0.model_0.data_0[i32(3)][i32(0)], pc_0.model_0.data_0[i32(3)][i32(1)], pc_0.model_0.data_0[i32(3)][i32(2)], pc_0.model_0.data_0[i32(3)][i32(3)])))).xyz;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldN_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S3 : pixelOutput_0 = pixelOutput_0( vec4<f32>(pc_0.color_0.xyz * vec3<f32>((0.25f + 0.75f * max(dot(normalize(_S2.worldN_1), normalize(vec3<f32>(0.34999999403953552f, 0.80000001192092896f, 0.5f))), 0.0f))), 1.0f) );
    return _S3;
}


)VRIWGSL";
