#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_pbrWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Ubo_std140_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) camPos_0 : vec4<f32>,
    @align(16) lights_0 : array<vec4<f32>, i32(4)>,
};

@binding(0) @group(0) var<uniform> uCam_0 : Ubo_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldPos_0 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
    @location(2) mat_0 : vec2<f32>,
    @location(3) color_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) normal_1 : vec3<f32>,
    @location(2) instA_0 : vec4<f32>,
    @location(3) instB_0 : vec4<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var world_0 : vec3<f32> = _S1.position_1 + _S1.instA_0.xyz;
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(world_0, 1.0f)) * (mat4x4<f32>(uCam_0.viewProj_0.data_0[i32(0)][i32(0)], uCam_0.viewProj_0.data_0[i32(0)][i32(1)], uCam_0.viewProj_0.data_0[i32(0)][i32(2)], uCam_0.viewProj_0.data_0[i32(0)][i32(3)], uCam_0.viewProj_0.data_0[i32(1)][i32(0)], uCam_0.viewProj_0.data_0[i32(1)][i32(1)], uCam_0.viewProj_0.data_0[i32(1)][i32(2)], uCam_0.viewProj_0.data_0[i32(1)][i32(3)], uCam_0.viewProj_0.data_0[i32(2)][i32(0)], uCam_0.viewProj_0.data_0[i32(2)][i32(1)], uCam_0.viewProj_0.data_0[i32(2)][i32(2)], uCam_0.viewProj_0.data_0[i32(2)][i32(3)], uCam_0.viewProj_0.data_0[i32(3)][i32(0)], uCam_0.viewProj_0.data_0[i32(3)][i32(1)], uCam_0.viewProj_0.data_0[i32(3)][i32(2)], uCam_0.viewProj_0.data_0[i32(3)][i32(3)]))));
    o_0.worldPos_0 = world_0;
    o_0.normal_0 = _S1.normal_1;
    o_0.mat_0 = vec2<f32>(_S1.instA_0.w, _S1.instB_0.w);
    o_0.color_0 = _S1.instB_0.xyz;
    return o_0;
}

fn D_GGX_0( dotNH_0 : f32,  roughness_0 : f32) -> f32
{
    var a_0 : f32 = roughness_0 * roughness_0;
    var a2_0 : f32 = a_0 * a_0;
    var denom_0 : f32 = dotNH_0 * dotNH_0 * (a2_0 - 1.0f) + 1.0f;
    return a2_0 / (3.14159274101257324f * denom_0 * denom_0);
}

fn G_SchlicksmithGGX_0( dotNL_0 : f32,  dotNV_0 : f32,  roughness_1 : f32) -> f32
{
    var r_0 : f32 = roughness_1 + 1.0f;
    var k_0 : f32 = r_0 * r_0 / 8.0f;
    var _S2 : f32 = 1.0f - k_0;
    return dotNL_0 / (dotNL_0 * _S2 + k_0) * (dotNV_0 / (dotNV_0 * _S2 + k_0));
}

fn F_Schlick_0( cosTheta_0 : f32,  metallic_0 : f32,  baseColor_0 : vec3<f32>) -> vec3<f32>
{
    var F0_0 : vec3<f32> = mix(vec3<f32>(0.03999999910593033f, 0.03999999910593033f, 0.03999999910593033f), baseColor_0, vec3<f32>(metallic_0));
    return F0_0 + (vec3<f32>(1.0f) - F0_0) * vec3<f32>(pow(1.0f - cosTheta_0, 5.0f));
}

fn BRDF_0( L_0 : vec3<f32>,  V_0 : vec3<f32>,  N_0 : vec3<f32>,  metallic_1 : f32,  roughness_2 : f32,  baseColor_1 : vec3<f32>) -> vec3<f32>
{
    var dotNV_1 : f32 = clamp(dot(N_0, V_0), 0.0f, 1.0f);
    var dotNL_1 : f32 = clamp(dot(N_0, L_0), 0.0f, 1.0f);
    var dotNH_1 : f32 = clamp(dot(N_0, normalize(V_0 + L_0)), 0.0f, 1.0f);
    const color_1 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var color_2 : vec3<f32>;
    if(dotNL_1 > 0.0f)
    {
        color_2 = vec3<f32>(D_GGX_0(dotNH_1, roughness_2)) * F_Schlick_0(dotNV_1, metallic_1, baseColor_1) * vec3<f32>(G_SchlicksmithGGX_0(dotNL_1, dotNV_1, max(0.05000000074505806f, roughness_2))) / vec3<f32>((4.0f * dotNL_1 * dotNV_1)) * vec3<f32>(dotNL_1);
    }
    else
    {
        color_2 = color_1;
    }
    return color_2;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldPos_1 : vec3<f32>,
    @location(1) normal_2 : vec3<f32>,
    @location(2) mat_1 : vec2<f32>,
    @location(3) color_3 : vec3<f32>,
};

@fragment
fn fragmentMain( _S3 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var _S4 : vec3<f32> = normalize(_S3.normal_2);
    var _S5 : vec3<f32> = normalize(uCam_0.camPos_0.xyz - _S3.worldPos_1);
    var _S6 : f32 = _S3.mat_1.x;
    var _S7 : f32 = _S3.mat_1.y;
    const _S8 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var i_0 : i32 = i32(0);
    var Lo_0 : vec3<f32> = _S8;
    for(;;)
    {
        if(i_0 < i32(4))
        {
        }
        else
        {
            break;
        }
        var Lo_1 : vec3<f32> = Lo_0 + BRDF_0(normalize(uCam_0.lights_0[i_0].xyz - _S3.worldPos_1), _S5, _S4, _S7, _S6, _S3.color_3);
        i_0 = i_0 + i32(1);
        Lo_0 = Lo_1;
    }
    var _S9 : pixelOutput_0 = pixelOutput_0( vec4<f32>(pow(_S3.color_3 * vec3<f32>(0.01999999955296516f) + Lo_0, vec3<f32>(0.4544999897480011f, 0.4544999897480011f, 0.4544999897480011f)), 1.0f) );
    return _S9;
}


)VRIWGSL";
