#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_shadowSceneWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Push_std430_0
{
    @align(16) model_0 : _MatrixStorage_float4x4std430_0,
};

var<uniform> pc_0 : Push_std430_0;
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_1 : array<vec4<f32>, i32(4)>,
};

struct Scene_std140_0
{
    @align(16) camViewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightViewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightDir_0 : vec4<f32>,
    @align(16) params_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> u_0 : Scene_std140_0;
@binding(1) @group(0) var shadowMap_0 : texture_depth_2d;

@binding(2) @group(0) var shadowSampler_0 : sampler_comparison;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldNormal_0 : vec3<f32>,
    @location(1) lightClip_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var wp_0 : vec4<f32> = (((vec4<f32>(_S1.position_1, 1.0f)) * (mat4x4<f32>(pc_0.model_0.data_0[i32(0)][i32(0)], pc_0.model_0.data_0[i32(0)][i32(1)], pc_0.model_0.data_0[i32(0)][i32(2)], pc_0.model_0.data_0[i32(0)][i32(3)], pc_0.model_0.data_0[i32(1)][i32(0)], pc_0.model_0.data_0[i32(1)][i32(1)], pc_0.model_0.data_0[i32(1)][i32(2)], pc_0.model_0.data_0[i32(1)][i32(3)], pc_0.model_0.data_0[i32(2)][i32(0)], pc_0.model_0.data_0[i32(2)][i32(1)], pc_0.model_0.data_0[i32(2)][i32(2)], pc_0.model_0.data_0[i32(2)][i32(3)], pc_0.model_0.data_0[i32(3)][i32(0)], pc_0.model_0.data_0[i32(3)][i32(1)], pc_0.model_0.data_0[i32(3)][i32(2)], pc_0.model_0.data_0[i32(3)][i32(3)]))));
    var o_0 : VSOutput_0;
    o_0.position_0 = (((wp_0) * (mat4x4<f32>(u_0.camViewProj_0.data_1[i32(0)][i32(0)], u_0.camViewProj_0.data_1[i32(0)][i32(1)], u_0.camViewProj_0.data_1[i32(0)][i32(2)], u_0.camViewProj_0.data_1[i32(0)][i32(3)], u_0.camViewProj_0.data_1[i32(1)][i32(0)], u_0.camViewProj_0.data_1[i32(1)][i32(1)], u_0.camViewProj_0.data_1[i32(1)][i32(2)], u_0.camViewProj_0.data_1[i32(1)][i32(3)], u_0.camViewProj_0.data_1[i32(2)][i32(0)], u_0.camViewProj_0.data_1[i32(2)][i32(1)], u_0.camViewProj_0.data_1[i32(2)][i32(2)], u_0.camViewProj_0.data_1[i32(2)][i32(3)], u_0.camViewProj_0.data_1[i32(3)][i32(0)], u_0.camViewProj_0.data_1[i32(3)][i32(1)], u_0.camViewProj_0.data_1[i32(3)][i32(2)], u_0.camViewProj_0.data_1[i32(3)][i32(3)]))));
    o_0.lightClip_0 = (((wp_0) * (mat4x4<f32>(u_0.lightViewProj_0.data_1[i32(0)][i32(0)], u_0.lightViewProj_0.data_1[i32(0)][i32(1)], u_0.lightViewProj_0.data_1[i32(0)][i32(2)], u_0.lightViewProj_0.data_1[i32(0)][i32(3)], u_0.lightViewProj_0.data_1[i32(1)][i32(0)], u_0.lightViewProj_0.data_1[i32(1)][i32(1)], u_0.lightViewProj_0.data_1[i32(1)][i32(2)], u_0.lightViewProj_0.data_1[i32(1)][i32(3)], u_0.lightViewProj_0.data_1[i32(2)][i32(0)], u_0.lightViewProj_0.data_1[i32(2)][i32(1)], u_0.lightViewProj_0.data_1[i32(2)][i32(2)], u_0.lightViewProj_0.data_1[i32(2)][i32(3)], u_0.lightViewProj_0.data_1[i32(3)][i32(0)], u_0.lightViewProj_0.data_1[i32(3)][i32(1)], u_0.lightViewProj_0.data_1[i32(3)][i32(2)], u_0.lightViewProj_0.data_1[i32(3)][i32(3)]))));
    var _S2 : mat4x4<f32> = mat4x4<f32>(pc_0.model_0.data_0[i32(0)][i32(0)], pc_0.model_0.data_0[i32(0)][i32(1)], pc_0.model_0.data_0[i32(0)][i32(2)], pc_0.model_0.data_0[i32(0)][i32(3)], pc_0.model_0.data_0[i32(1)][i32(0)], pc_0.model_0.data_0[i32(1)][i32(1)], pc_0.model_0.data_0[i32(1)][i32(2)], pc_0.model_0.data_0[i32(1)][i32(3)], pc_0.model_0.data_0[i32(2)][i32(0)], pc_0.model_0.data_0[i32(2)][i32(1)], pc_0.model_0.data_0[i32(2)][i32(2)], pc_0.model_0.data_0[i32(2)][i32(3)], pc_0.model_0.data_0[i32(3)][i32(0)], pc_0.model_0.data_0[i32(3)][i32(1)], pc_0.model_0.data_0[i32(3)][i32(2)], pc_0.model_0.data_0[i32(3)][i32(3)]);
    o_0.worldNormal_0 = (((_S1.normal_0) * (mat3x3<f32>(_S2[i32(0)].xyz, _S2[i32(1)].xyz, _S2[i32(2)].xyz))));
    return o_0;
}

fn samplePcf_0( uv_0 : vec2<f32>,  ref_0 : f32) -> f32
{
    var _S3 : f32 = u_0.params_0.y;
    var y_0 : i32 = i32(-1);
    var sum_0 : f32 = 0.0f;
    for(;;)
    {
        if(y_0 <= i32(1))
        {
        }
        else
        {
            break;
        }
        var x_0 : i32 = i32(-1);
        for(;;)
        {
            if(x_0 <= i32(1))
            {
            }
            else
            {
                break;
            }
            var sum_1 : f32 = sum_0 + (textureSampleCompareLevel((shadowMap_0), (shadowSampler_0), (uv_0 + vec2<f32>(f32(x_0), f32(y_0)) * vec2<f32>(_S3)), (ref_0)));
            x_0 = x_0 + i32(1);
            sum_0 = sum_1;
        }
        y_0 = y_0 + i32(1);
    }
    return sum_0 / 9.0f;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldNormal_1 : vec3<f32>,
    @location(1) lightClip_1 : vec4<f32>,
};

@fragment
fn fragmentMain( _S4 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var ndc_0 : vec3<f32> = _S4.lightClip_1.xyz / vec3<f32>(_S4.lightClip_1.w);
    var _S5 : vec2<f32> = vec2<f32>(0.5f);
    var uv_1 : vec2<f32> = ndc_0.xy * _S5 + _S5;
    var ref_1 : f32;
    if((u_0.params_0.z) > 0.5f)
    {
        ref_1 = ndc_0.z;
    }
    else
    {
        ref_1 = ndc_0.z * 0.5f + 0.5f;
    }
    var ref_2 : f32 = ref_1 - u_0.params_0.x;
    var _S6 : f32 = uv_1.x;
    var _S7 : bool;
    if(_S6 == (saturate(_S6)))
    {
        var _S8 : f32 = uv_1.y;
        _S7 = _S8 == (saturate(_S8));
    }
    else
    {
        _S7 = false;
    }
    if(_S7)
    {
        _S7 = (ndc_0.z) <= 1.0f;
    }
    else
    {
        _S7 = false;
    }
    var shadow_0 : f32;
    if(_S7)
    {
        shadow_0 = samplePcf_0(uv_1, ref_2);
    }
    else
    {
        shadow_0 = 1.0f;
    }
    var ambient_0 : f32 = u_0.params_0.w;
    var _S9 : pixelOutput_0 = pixelOutput_0( vec4<f32>(vec3<f32>(0.85000002384185791f, 0.85000002384185791f, 0.87999999523162842f) * vec3<f32>((ambient_0 + (1.0f - ambient_0) * max(dot(normalize(_S4.worldNormal_1), normalize(u_0.lightDir_0.xyz)), 0.0f) * shadow_0)), 1.0f) );
    return _S9;
}


)VRIWGSL";
