#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_stencilFillWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Push_std430_0
{
    @align(16) model_0 : _MatrixStorage_float4x4std430_0,
};

var<uniform> pc_0 : Push_std430_0;
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_1 : array<vec4<f32>, i32(4)>,
};

struct Scene_std140_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightDir_0 : vec4<f32>,
    @align(16) outlineColor_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> u_0 : Scene_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldNormal_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = ((((((vec4<f32>(_S1.position_1, 1.0f)) * (mat4x4<f32>(pc_0.model_0.data_0[i32(0)][i32(0)], pc_0.model_0.data_0[i32(0)][i32(1)], pc_0.model_0.data_0[i32(0)][i32(2)], pc_0.model_0.data_0[i32(0)][i32(3)], pc_0.model_0.data_0[i32(1)][i32(0)], pc_0.model_0.data_0[i32(1)][i32(1)], pc_0.model_0.data_0[i32(1)][i32(2)], pc_0.model_0.data_0[i32(1)][i32(3)], pc_0.model_0.data_0[i32(2)][i32(0)], pc_0.model_0.data_0[i32(2)][i32(1)], pc_0.model_0.data_0[i32(2)][i32(2)], pc_0.model_0.data_0[i32(2)][i32(3)], pc_0.model_0.data_0[i32(3)][i32(0)], pc_0.model_0.data_0[i32(3)][i32(1)], pc_0.model_0.data_0[i32(3)][i32(2)], pc_0.model_0.data_0[i32(3)][i32(3)]))))) * (mat4x4<f32>(u_0.viewProj_0.data_1[i32(0)][i32(0)], u_0.viewProj_0.data_1[i32(0)][i32(1)], u_0.viewProj_0.data_1[i32(0)][i32(2)], u_0.viewProj_0.data_1[i32(0)][i32(3)], u_0.viewProj_0.data_1[i32(1)][i32(0)], u_0.viewProj_0.data_1[i32(1)][i32(1)], u_0.viewProj_0.data_1[i32(1)][i32(2)], u_0.viewProj_0.data_1[i32(1)][i32(3)], u_0.viewProj_0.data_1[i32(2)][i32(0)], u_0.viewProj_0.data_1[i32(2)][i32(1)], u_0.viewProj_0.data_1[i32(2)][i32(2)], u_0.viewProj_0.data_1[i32(2)][i32(3)], u_0.viewProj_0.data_1[i32(3)][i32(0)], u_0.viewProj_0.data_1[i32(3)][i32(1)], u_0.viewProj_0.data_1[i32(3)][i32(2)], u_0.viewProj_0.data_1[i32(3)][i32(3)]))));
    var _S2 : mat4x4<f32> = mat4x4<f32>(pc_0.model_0.data_0[i32(0)][i32(0)], pc_0.model_0.data_0[i32(0)][i32(1)], pc_0.model_0.data_0[i32(0)][i32(2)], pc_0.model_0.data_0[i32(0)][i32(3)], pc_0.model_0.data_0[i32(1)][i32(0)], pc_0.model_0.data_0[i32(1)][i32(1)], pc_0.model_0.data_0[i32(1)][i32(2)], pc_0.model_0.data_0[i32(1)][i32(3)], pc_0.model_0.data_0[i32(2)][i32(0)], pc_0.model_0.data_0[i32(2)][i32(1)], pc_0.model_0.data_0[i32(2)][i32(2)], pc_0.model_0.data_0[i32(2)][i32(3)], pc_0.model_0.data_0[i32(3)][i32(0)], pc_0.model_0.data_0[i32(3)][i32(1)], pc_0.model_0.data_0[i32(3)][i32(2)], pc_0.model_0.data_0[i32(3)][i32(3)]);
    o_0.worldNormal_0 = (((_S1.normal_0) * (mat3x3<f32>(_S2[i32(0)].xyz, _S2[i32(1)].xyz, _S2[i32(2)].xyz))));
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldNormal_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S3 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var _S4 : pixelOutput_0 = pixelOutput_0( vec4<f32>(vec3<f32>(0.85000002384185791f, 0.55000001192092896f, 0.30000001192092896f) * vec3<f32>((0.25f + 0.75f * max(dot(normalize(_S3.worldNormal_1), normalize(u_0.lightDir_0.xyz)), 0.0f))), 1.0f) );
    return _S4;
}


)VRIWGSL";
