#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_terrainBasicWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Camera_std140_0
{
    @align(16) mvp_0 : _MatrixStorage_float4x4std140_0,
    @align(16) params_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> uCam_0 : Camera_std140_0;
fn TerrainHeight_0( xz_0 : vec2<f32>) -> f32
{
    var _S1 : f32 = xz_0.x;
    var _S2 : f32 = xz_0.y;
    return 0.34999999403953552f * sin(_S1 * 2.09999990463256836f) * cos(_S2 * 1.70000004768371582f) + 0.18000000715255737f * sin(_S1 * 4.69999980926513672f + 1.29999995231628418f) * cos(_S2 * 3.90000009536743164f + 0.60000002384185791f);
}

fn TerrainNormal_0( xz_1 : vec2<f32>) -> vec3<f32>
{
    var _S3 : f32 = xz_1.x;
    var _S4 : f32 = _S3 * 2.09999990463256836f;
    var _S5 : f32 = xz_1.y;
    var _S6 : f32 = _S5 * 1.70000004768371582f;
    var _S7 : f32 = _S3 * 4.69999980926513672f + 1.29999995231628418f;
    var _S8 : f32 = _S5 * 3.90000009536743164f + 0.60000002384185791f;
    return normalize(vec3<f32>(- (0.73499995470046997f * cos(_S4) * cos(_S6) + 0.84600001573562622f * cos(_S7) * cos(_S8)), 1.0f, - (-0.59500002861022949f * sin(_S4) * sin(_S6) - 0.70200002193450928f * sin(_S7) * sin(_S8))));
}

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) height_0 : f32,
    @location(1) normal_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) pos_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S9 : vertexInput_0) -> VSOutput_0
{
    var p_0 : vec3<f32> = _S9.pos_0;
    var h_0 : f32 = TerrainHeight_0(_S9.pos_0.xz);
    p_0[i32(1)] = h_0 * uCam_0.params_0.y;
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(p_0, 1.0f)) * (mat4x4<f32>(uCam_0.mvp_0.data_0[i32(0)][i32(0)], uCam_0.mvp_0.data_0[i32(0)][i32(1)], uCam_0.mvp_0.data_0[i32(0)][i32(2)], uCam_0.mvp_0.data_0[i32(0)][i32(3)], uCam_0.mvp_0.data_0[i32(1)][i32(0)], uCam_0.mvp_0.data_0[i32(1)][i32(1)], uCam_0.mvp_0.data_0[i32(1)][i32(2)], uCam_0.mvp_0.data_0[i32(1)][i32(3)], uCam_0.mvp_0.data_0[i32(2)][i32(0)], uCam_0.mvp_0.data_0[i32(2)][i32(1)], uCam_0.mvp_0.data_0[i32(2)][i32(2)], uCam_0.mvp_0.data_0[i32(2)][i32(3)], uCam_0.mvp_0.data_0[i32(3)][i32(0)], uCam_0.mvp_0.data_0[i32(3)][i32(1)], uCam_0.mvp_0.data_0[i32(3)][i32(2)], uCam_0.mvp_0.data_0[i32(3)][i32(3)]))));
    o_0.height_0 = h_0;
    o_0.normal_0 = TerrainNormal_0(p_0.xz);
    return o_0;
}

fn TerrainColor_0( h_1 : f32,  n_0 : vec3<f32>) -> vec3<f32>
{
    var _S10 : f32 = max(dot(n_0, normalize(vec3<f32>(0.40000000596046448f, 0.89999997615814209f, 0.30000001192092896f))), 0.0f);
    var t_0 : f32 = saturate(h_1 * 1.39999997615814209f + 0.5f);
    const low_0 : vec3<f32> = vec3<f32>(0.15999999642372131f, 0.41999998688697815f, 0.20000000298023224f);
    const mid_0 : vec3<f32> = vec3<f32>(0.44999998807907104f, 0.36000001430511475f, 0.23999999463558197f);
    const high_0 : vec3<f32> = vec3<f32>(0.92000001668930054f, 0.93999999761581421f, 0.98000001907348633f);
    var base_0 : vec3<f32>;
    if(t_0 < 0.5f)
    {
        base_0 = mix(low_0, mid_0, vec3<f32>((t_0 * 2.0f)));
    }
    else
    {
        base_0 = mix(mid_0, high_0, vec3<f32>((t_0 * 2.0f - 1.0f)));
    }
    return base_0 * vec3<f32>((0.25f + 0.75f * _S10));
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) height_1 : f32,
    @location(1) normal_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S11 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S12 : pixelOutput_0 = pixelOutput_0( vec4<f32>(TerrainColor_0(_S11.height_1, normalize(_S11.normal_1)), 1.0f) );
    return _S12;
}


)VRIWGSL";
