#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_vrsSceneWgsl[] = R"VRIWGSL(
struct Push_std430_0
{
    @align(16) p_0 : vec4<f32>,
};

var<uniform> pc_0 : Push_std430_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var p_1 : vec2<f32> = vec2<f32>(f32((((vid_0 << (u32(1)))) & (u32(2)))), f32((vid_0 & (u32(2)))));
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_1 * vec2<f32>(2.0f) - vec2<f32>(1.0f), 0.0f, 1.0f);
    o_0.uv_0 = p_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
};

@fragment
fn fragmentMain( _S1 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var uv_2 : vec2<f32> = _S1.uv_1;
    uv_2[i32(0)] = uv_2[i32(0)] * pc_0.p_0.y;
    var _S2 : f32 = pc_0.p_0.x;
    var _S3 : i32 = i32(pc_0.p_0.z + 0.5f);
    var i_0 : i32 = i32(1);
    var v_0 : f32 = 0.0f;
    for(;;)
    {
        if(i_0 <= _S3)
        {
        }
        else
        {
            break;
        }
        var fi_0 : f32 = f32(i_0);
        var v_1 : f32 = v_0 + sin(uv_2.x * fi_0 * 9.0f + _S2 * (0.69999998807907104f + fi_0 * 0.10999999940395355f)) * cos(uv_2.y * fi_0 * 7.0f - _S2 * (0.5f + fi_0 * 0.07000000029802322f)) / fi_0;
        i_0 = i_0 + i32(1);
        v_0 = v_1;
    }
    var _S4 : f32 = v_0 * 0.60000002384185791f * 6.28319978713989258f;
    var color_0 : vec3<f32> = vec3<f32>(0.5f + 0.5f * sin(_S4), 0.5f + 0.5f * sin(_S4 + 2.09400010108947754f), 0.5f + 0.5f * sin(_S4 + 4.18900012969970703f));
    var g_0 : vec2<f32> = fract(uv_2 * vec2<f32>(96.0f));
    var checker_0 : f32;
    if(((g_0.x) < 0.5f) != ((g_0.y) < 0.5f))
    {
        checker_0 = 1.0f;
    }
    else
    {
        checker_0 = 0.81999999284744263f;
    }
    var _S5 : pixelOutput_0 = pixelOutput_0( vec4<f32>(color_0 * vec3<f32>(checker_0), 1.0f) );
    return _S5;
}


)VRIWGSL";
