#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_waveVisBasicWgsl[] = R"VRIWGSL(
struct Params_std140_0
{
    @align(16) time_0 : f32,
    @align(4) width_0 : u32,
    @align(8) height_0 : u32,
    @align(4) pad_0 : u32,
};

@binding(0) @group(0) var<uniform> uParams_0 : Params_std140_0;
@binding(1) @group(0) var uImage_0 : texture_storage_2d<rgba8unorm, write>;

fn Hue_0( h_0 : f32) -> vec3<f32>
{
    var _S1 : f32 = h_0 * 6.28319978713989258f;
    return vec3<f32>(0.5f + 0.5f * sin(_S1), 0.5f + 0.5f * sin(_S1 + 2.09400010108947754f), 0.5f + 0.5f * sin(_S1 + 4.18900012969970703f));
}

@compute
@workgroup_size(64, 1, 1)
fn computeMain(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var _S2 : u32 = tid_0.x;
    var _S3 : bool;
    if(_S2 >= (uParams_0.width_0))
    {
        _S3 = true;
    }
    else
    {
        _S3 = (tid_0.y) >= (uParams_0.height_0);
    }
    if(_S3)
    {
        return;
    }
    var laneIdx_0 : u32 = _S2 % u32(32);
    var _S4 : u32 = tid_0.y;
    var band_0 : f32 = f32(uParams_0.height_0 - u32(1) - _S4) / f32(uParams_0.height_0);
    var t_0 : f32 = uParams_0.time_0;
    var color_0 : vec3<f32>;
    if(band_0 < 0.33329999446868896f)
    {
        color_0 = Hue_0(f32(laneIdx_0) / 32.0f);
    }
    else
    {
        if(band_0 < 0.66670000553131104f)
        {
            var ramp_0 : f32 = fract(f32(laneIdx_0) / 32.0f + t_0 * 0.25f);
            color_0 = vec3<f32>(ramp_0, ramp_0 * 0.80000001192092896f, 1.0f - ramp_0) * vec3<f32>(0.89999997615814209f);
        }
        else
        {
            var _S5 : u32 = _S2 - laneIdx_0;
            var i_0 : u32 = u32(0);
            var bits_0 : u32 = u32(0);
            for(;;)
            {
                if(i_0 < u32(32))
                {
                }
                else
                {
                    break;
                }
                if((sin(f32(_S5 + i_0) * 0.10999999940395355f + t_0 * 2.0f + f32(i_0) * 0.31000000238418579f)) > 0.0f)
                {
                    bits_0 = bits_0 + u32(1);
                }
                i_0 = i_0 + u32(1);
            }
            color_0 = Hue_0(f32(bits_0) / 32.0f * 0.69999998807907104f + 0.15000000596046448f) * vec3<f32>(0.85000002384185791f);
        }
    }
    if((fract(f32(_S4) * 3.0f / f32(uParams_0.height_0))) < 0.01499999966472387f)
    {
        color_0 = vec3<f32>(0.05000000074505806f, 0.05000000074505806f, 0.07999999821186066f);
    }
    textureStore((uImage_0), (tid_0.xy), (vec4<f32>(color_0, 1.0f)));
    return;
}


)VRIWGSL";
