#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_waveVisFragWgsl[] = R"VRIWGSL(
struct Params_std140_0
{
    @align(16) time_0 : f32,
    @align(4) width_0 : u32,
    @align(8) height_0 : u32,
    @align(4) pad_0 : u32,
};

@binding(0) @group(0) var<uniform> uParams_0 : Params_std140_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var p_0 : vec2<f32> = vec2<f32>(f32((((vid_0 << (u32(1)))) & (u32(2)))), f32((vid_0 & (u32(2)))));
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_0 * vec2<f32>(2.0f) - vec2<f32>(1.0f), 0.0f, 1.0f);
    o_0.uv_0 = p_0;
    return o_0;
}

fn Hue_0( h_0 : f32) -> vec3<f32>
{
    var _S1 : f32 = h_0 * 6.28319978713989258f;
    return vec3<f32>(0.5f + 0.5f * sin(_S1), 0.5f + 0.5f * sin(_S1 + 2.09400010108947754f), 0.5f + 0.5f * sin(_S1 + 4.18900012969970703f));
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var x_0 : f32 = _S2.uv_1.x * f32(uParams_0.width_0);
    var lane_0 : f32 = x_0 - 32.0f * floor(x_0 / 32.0f);
    var t_0 : f32 = uParams_0.time_0;
    var _S3 : f32 = _S2.uv_1.y;
    var color_0 : vec3<f32>;
    if(_S3 < 0.33329999446868896f)
    {
        color_0 = Hue_0(lane_0 / 32.0f);
    }
    else
    {
        if(_S3 < 0.66670000553131104f)
        {
            var ramp_0 : f32 = fract(lane_0 / 32.0f + t_0 * 0.25f);
            color_0 = vec3<f32>(ramp_0, ramp_0 * 0.80000001192092896f, 1.0f - ramp_0) * vec3<f32>(0.89999997615814209f);
        }
        else
        {
            var _S4 : f32 = x_0 - lane_0;
            var i_0 : f32 = 0.0f;
            var bits_0 : f32 = 0.0f;
            for(;;)
            {
                if(i_0 < 32.0f)
                {
                }
                else
                {
                    break;
                }
                if((sin((_S4 + i_0) * 0.10999999940395355f + t_0 * 2.0f + i_0 * 0.31000000238418579f)) > 0.0f)
                {
                    bits_0 = bits_0 + 1.0f;
                }
                i_0 = i_0 + 1.0f;
            }
            color_0 = Hue_0(bits_0 / 32.0f * 0.69999998807907104f + 0.15000000596046448f) * vec3<f32>(0.85000002384185791f);
        }
    }
    if((fract(_S3 * 3.0f)) < 0.01499999966472387f)
    {
        color_0 = vec3<f32>(0.05000000074505806f, 0.05000000074505806f, 0.07999999821186066f);
    }
    var _S5 : pixelOutput_0 = pixelOutput_0( vec4<f32>(color_0, 1.0f) );
    return _S5;
}


)VRIWGSL";
