#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_deferredMrtWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Camera_std140_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4std140_0,
};

@binding(0) @group(0) var<uniform> uCam_0 : Camera_std140_0;
@binding(1) @group(0) var uTex_0 : texture_2d<f32>;

@binding(2) @group(0) var uSmp_0 : sampler;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldPos_0 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
    @location(2) uv_0 : vec2<f32>,
    @location(3) tint_0 : vec3<f32>,
    @location(4) spec_0 : f32,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) normal_1 : vec3<f32>,
    @location(2) uv_1 : vec2<f32>,
    @location(3) instA_0 : vec4<f32>,
    @location(4) instB_0 : vec4<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var world_0 : vec3<f32> = _S1.position_1 + _S1.instA_0.xyz;
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(world_0, 1.0f)) * (mat4x4<f32>(uCam_0.viewProj_0.data_0[i32(0)][i32(0)], uCam_0.viewProj_0.data_0[i32(0)][i32(1)], uCam_0.viewProj_0.data_0[i32(0)][i32(2)], uCam_0.viewProj_0.data_0[i32(0)][i32(3)], uCam_0.viewProj_0.data_0[i32(1)][i32(0)], uCam_0.viewProj_0.data_0[i32(1)][i32(1)], uCam_0.viewProj_0.data_0[i32(1)][i32(2)], uCam_0.viewProj_0.data_0[i32(1)][i32(3)], uCam_0.viewProj_0.data_0[i32(2)][i32(0)], uCam_0.viewProj_0.data_0[i32(2)][i32(1)], uCam_0.viewProj_0.data_0[i32(2)][i32(2)], uCam_0.viewProj_0.data_0[i32(2)][i32(3)], uCam_0.viewProj_0.data_0[i32(3)][i32(0)], uCam_0.viewProj_0.data_0[i32(3)][i32(1)], uCam_0.viewProj_0.data_0[i32(3)][i32(2)], uCam_0.viewProj_0.data_0[i32(3)][i32(3)]))));
    o_0.worldPos_0 = world_0;
    o_0.normal_0 = _S1.normal_1;
    o_0.uv_0 = _S1.uv_1 * vec2<f32>(_S1.instA_0.w);
    o_0.tint_0 = _S1.instB_0.xyz;
    o_0.spec_0 = _S1.instB_0.w;
    return o_0;
}

struct GBuffer_0
{
    @location(0) position_2 : vec4<f32>,
    @location(1) normal_2 : vec4<f32>,
    @location(2) albedoSpec_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldPos_1 : vec3<f32>,
    @location(1) normal_3 : vec3<f32>,
    @location(2) uv_2 : vec2<f32>,
    @location(3) tint_1 : vec3<f32>,
    @location(4) spec_1 : f32,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_3 : vec4<f32>) -> GBuffer_0
{
    var tex_0 : vec4<f32> = (textureSample((uTex_0), (uSmp_0), (_S2.uv_2)));
    var N_0 : vec3<f32> = normalize(_S2.normal_3);
    var o_1 : GBuffer_0;
    o_1.position_2 = vec4<f32>(_S2.worldPos_1, 1.0f);
    var _S3 : vec3<f32> = vec3<f32>(0.5f);
    o_1.normal_2 = vec4<f32>(_S3 + _S3 * N_0, 1.0f);
    o_1.albedoSpec_0 = vec4<f32>(tex_0.xyz * _S2.tint_1, _S2.spec_1);
    return o_1;
}


)VRIWGSL";
