#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_imguiWgsl[] = R"VRIWGSL(
struct Ortho_std430_0
{
    @align(8) scale_0 : vec2<f32>,
    @align(8) translate_0 : vec2<f32>,
};

var<uniform> pc_0 : Ortho_std430_0;
@binding(0) @group(0) var uTex_0 : texture_2d<f32>;

@binding(1) @group(0) var uSmp_0 : sampler;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
    @location(1) col_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) pos_0 : vec2<f32>,
    @location(1) uv_1 : vec2<f32>,
    @location(2) col_1 : vec4<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(_S1.pos_0 * pc_0.scale_0 + pc_0.translate_0, 0.0f, 1.0f);
    o_0.uv_0 = _S1.uv_1;
    o_0.col_0 = _S1.col_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_2 : vec2<f32>,
    @location(1) col_2 : vec4<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S3 : pixelOutput_0 = pixelOutput_0( _S2.col_2 * (textureSample((uTex_0), (uSmp_0), (_S2.uv_2))) );
    return _S3;
}


)VRIWGSL";
