#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_normalmapWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Ubo_std140_0
{
    @align(16) mvp_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightPos_0 : vec4<f32>,
    @align(16) camPos_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> u_0 : Ubo_std140_0;
@binding(2) @group(0) var normalTex_0 : texture_2d<f32>;

@binding(3) @group(0) var samp_0 : sampler;

@binding(1) @group(0) var colorTex_0 : texture_2d<f32>;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) worldPos_0 : vec3<f32>,
    @location(1) uv_0 : vec2<f32>,
    @location(2) T_0 : vec3<f32>,
    @location(3) B_0 : vec3<f32>,
    @location(4) N_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
    @location(2) tangent_0 : vec3<f32>,
    @location(3) uv_1 : vec2<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(_S1.position_1, 1.0f)) * (mat4x4<f32>(u_0.mvp_0.data_0[i32(0)][i32(0)], u_0.mvp_0.data_0[i32(0)][i32(1)], u_0.mvp_0.data_0[i32(0)][i32(2)], u_0.mvp_0.data_0[i32(0)][i32(3)], u_0.mvp_0.data_0[i32(1)][i32(0)], u_0.mvp_0.data_0[i32(1)][i32(1)], u_0.mvp_0.data_0[i32(1)][i32(2)], u_0.mvp_0.data_0[i32(1)][i32(3)], u_0.mvp_0.data_0[i32(2)][i32(0)], u_0.mvp_0.data_0[i32(2)][i32(1)], u_0.mvp_0.data_0[i32(2)][i32(2)], u_0.mvp_0.data_0[i32(2)][i32(3)], u_0.mvp_0.data_0[i32(3)][i32(0)], u_0.mvp_0.data_0[i32(3)][i32(1)], u_0.mvp_0.data_0[i32(3)][i32(2)], u_0.mvp_0.data_0[i32(3)][i32(3)]))));
    o_0.worldPos_0 = _S1.position_1;
    o_0.uv_0 = _S1.uv_1;
    o_0.N_0 = _S1.normal_0;
    o_0.T_0 = _S1.tangent_0;
    o_0.B_0 = cross(_S1.normal_0, _S1.tangent_0);
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) worldPos_1 : vec3<f32>,
    @location(1) uv_2 : vec2<f32>,
    @location(2) T_1 : vec3<f32>,
    @location(3) B_1 : vec3<f32>,
    @location(4) N_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var tn_0 : vec3<f32> = (textureSample((normalTex_0), (samp_0), (_S2.uv_2))).xyz * vec3<f32>(2.0f) - vec3<f32>(1.0f);
    var n_0 : vec3<f32> = normalize(normalize(_S2.T_1) * vec3<f32>(tn_0.x) + normalize(_S2.B_1) * vec3<f32>(tn_0.y) + normalize(_S2.N_1) * vec3<f32>(tn_0.z));
    var L_0 : vec3<f32> = normalize(u_0.lightPos_0.xyz - _S2.worldPos_1);
    var _S3 : pixelOutput_0 = pixelOutput_0( vec4<f32>((textureSample((colorTex_0), (samp_0), (_S2.uv_2))).xyz * vec3<f32>((0.15000000596046448f + max(dot(n_0, L_0), 0.0f))) + vec3<f32>(0.60000002384185791f, 0.60000002384185791f, 0.60000002384185791f) * vec3<f32>(pow(max(dot(n_0, normalize(L_0 + normalize(u_0.camPos_0.xyz - _S2.worldPos_1))), 0.0f), 32.0f)), 1.0f) );
    return _S3;
}


)VRIWGSL";
