#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_rtPathtraceSoftwareWgsl[] = R"VRIWGSL(
@binding(1) @group(0) var outImage_0 : texture_storage_2d<rgba8unorm, write>;

struct PtCamera_std140_0
{
    @align(16) eye_0 : vec4<f32>,
    @align(16) camRight_0 : vec4<f32>,
    @align(16) camUp_0 : vec4<f32>,
    @align(16) camFwd_0 : vec4<f32>,
    @align(16) sky_0 : vec4<f32>,
    @align(16) control_0 : vec4<f32>,
};

@binding(2) @group(0) var<uniform> cam_0 : PtCamera_std140_0;
struct Vertex_std430_0
{
    @align(16) a_0 : vec4<f32>,
    @align(16) b_0 : vec4<f32>,
};

@binding(3) @group(0) var<storage, read_write> vertices_0 : array<Vertex_std430_0>;

@binding(4) @group(0) var<storage, read_write> indices_0 : array<u32>;

struct BvhNode_std430_0
{
    @align(16) aabbMin_0 : vec3<f32>,
    @align(4) leftOrFirst_0 : u32,
    @align(16) aabbMax_0 : vec3<f32>,
    @align(4) countOrSecond_0 : u32,
};

@binding(9) @group(0) var<storage, read_write> bvhNodes_0 : array<BvhNode_std430_0>;

struct TriRef_std430_0
{
    @align(4) indexBase_0 : u32,
    @align(4) geomNodeIndex_0 : u32,
};

@binding(10) @group(0) var<storage, read_write> triRefs_0 : array<TriRef_std430_0>;

struct GeometryNode_std430_0
{
    @align(4) firstIndex_0 : u32,
    @align(4) baseColorTexture_0 : i32,
    @align(4) occlusionTexture_0 : i32,
    @align(4) _pad_0 : u32,
};

@binding(5) @group(0) var<storage, read_write> geometryNodes_0 : array<GeometryNode_std430_0>;

@binding(7) @group(0) var textures_0 : texture_2d_array<f32>;

@binding(6) @group(0) var samp_0 : sampler;

@binding(8) @group(0) var<storage, read_write> accumBuffer_0 : array<vec4<f32>>;

fn pcg_0( s_0 : ptr<function, u32>) -> u32
{
    var _S1 : u32 = (*s_0) * u32(747796405) + u32(2891336453);
    (*s_0) = _S1;
    var w_0 : u32 = ((((_S1 >> ((((_S1 >> (u32(28)))) + u32(4))))) ^ (_S1))) * u32(277803737);
    return (((w_0 >> (u32(22)))) ^ (w_0));
}

fn rnd_0( s_1 : ptr<function, u32>) -> f32
{
    var _S2 : u32 = pcg_0(&((*s_1)));
    return f32((_S2 & (u32(16777215)))) / 1.6777216e+07f;
}

fn rnd_1( s_2 : ptr<function, u32>) -> f32
{
    var _S3 : u32 = pcg_0(&((*s_2)));
    return f32((_S3 & (u32(16777215)))) / 1.6777216e+07f;
}

fn intersectAabb_0( ro_0 : vec3<f32>,  invRd_0 : vec3<f32>,  bmin_0 : vec3<f32>,  bmax_0 : vec3<f32>,  tMax_0 : f32) -> f32
{
    var t0_0 : vec3<f32> = (bmin_0 - ro_0) * invRd_0;
    var t1_0 : vec3<f32> = (bmax_0 - ro_0) * invRd_0;
    var mn_0 : vec3<f32> = min(t0_0, t1_0);
    var mx_0 : vec3<f32> = max(t0_0, t1_0);
    var _S4 : f32 = max(max(mn_0.x, mn_0.y), max(mn_0.z, 0.0f));
    var _S5 : f32;
    if((min(min(mx_0.x, mx_0.y), min(mx_0.z, tMax_0))) >= _S4)
    {
        _S5 = _S4;
    }
    else
    {
        _S5 = 1.00000001504746622e+30f;
    }
    return _S5;
}

fn nodeLeftOrFirst_0( n_0 : ptr<function, BvhNode_std430_0>) -> u32
{
    return (*n_0).leftOrFirst_0;
}

fn nodeIsLeaf_0( n_1 : ptr<function, BvhNode_std430_0>) -> bool
{
    return ((((*n_1).countOrSecond_0) & (u32(2147483648)))) != u32(0);
}

fn nodeCountOrSecond_0( n_2 : ptr<function, BvhNode_std430_0>) -> u32
{
    return (*n_2).countOrSecond_0;
}

fn vPos_0( v_0 : ptr<function, Vertex_std430_0>) -> vec3<f32>
{
    return (*v_0).a_0.xyz;
}

struct Hit_0
{
     t_0 : f32,
     u_0 : f32,
     v_1 : f32,
     indexBase_1 : u32,
     geomNodeIndex_1 : u32,
     hit_0 : bool,
};

fn intersectTri_0( ro_1 : vec3<f32>,  rd_0 : vec3<f32>,  p0_0 : vec3<f32>,  p1_0 : vec3<f32>,  p2_0 : vec3<f32>,  hit_1 : ptr<function, Hit_0>) -> bool
{
    var e1_0 : vec3<f32> = p1_0 - p0_0;
    var e2_0 : vec3<f32> = p2_0 - p0_0;
    var p_0 : vec3<f32> = cross(rd_0, e2_0);
    var det_0 : f32 = dot(e1_0, p_0);
    if((abs(det_0)) < 1.00000001168609742e-07f)
    {
        return false;
    }
    var invDet_0 : f32 = 1.0f / det_0;
    var tv_0 : vec3<f32> = ro_1 - p0_0;
    var u_1 : f32 = dot(tv_0, p_0) * invDet_0;
    var _S6 : bool;
    if(u_1 < 0.0f)
    {
        _S6 = true;
    }
    else
    {
        _S6 = u_1 > 1.0f;
    }
    if(_S6)
    {
        return false;
    }
    var q_0 : vec3<f32> = cross(tv_0, e1_0);
    var v_2 : f32 = dot(rd_0, q_0) * invDet_0;
    if(v_2 < 0.0f)
    {
        _S6 = true;
    }
    else
    {
        _S6 = (u_1 + v_2) > 1.0f;
    }
    if(_S6)
    {
        return false;
    }
    var t_1 : f32 = dot(e2_0, q_0) * invDet_0;
    if(t_1 <= 0.00100000004749745f)
    {
        _S6 = true;
    }
    else
    {
        _S6 = t_1 >= ((*hit_1).t_0);
    }
    if(_S6)
    {
        return false;
    }
    (*hit_1).t_0 = t_1;
    (*hit_1).u_0 = u_1;
    (*hit_1).v_1 = v_2;
    (*hit_1).hit_0 = true;
    return true;
}

fn skyColor_0( dir_0 : vec3<f32>) -> vec3<f32>
{
    return mix(vec3<f32>(0.55000001192092896f, 0.60000002384185791f, 0.6600000262260437f), cam_0.sky_0.xyz, vec3<f32>(saturate(dir_0.y * 0.5f + 0.5f))) * vec3<f32>(cam_0.sky_0.w);
}

fn vNormal_0( v_3 : ptr<function, Vertex_std430_0>) -> vec3<f32>
{
    return vec3<f32>((*v_3).a_0.w, (*v_3).b_0.x, (*v_3).b_0.y);
}

fn vUv_0( v_4 : ptr<function, Vertex_std430_0>) -> vec2<f32>
{
    return (*v_4).b_0.zw;
}

fn cosineSample_0( n_3 : vec3<f32>,  s_3 : ptr<function, u32>) -> vec3<f32>
{
    var u1_0 : f32 = rnd_1(&((*s_3)));
    var u2_0 : f32 = rnd_1(&((*s_3)));
    var r_0 : f32 = sqrt(u1_0);
    var phi_0 : f32 = 6.28318548202514648f * u2_0;
    var up_0 : vec3<f32>;
    if((abs(n_3.y)) < 0.99000000953674316f)
    {
        up_0 = vec3<f32>(0.0f, 1.0f, 0.0f);
    }
    else
    {
        up_0 = vec3<f32>(1.0f, 0.0f, 0.0f);
    }
    var t_2 : vec3<f32> = normalize(cross(up_0, n_3));
    return normalize(t_2 * vec3<f32>((r_0 * cos(phi_0))) + cross(n_3, t_2) * vec3<f32>((r_0 * sin(phi_0))) + n_3 * vec3<f32>(sqrt(max(0.0f, 1.0f - u1_0))));
}

fn traceBvh_0( _S7 : vec3<f32>,  _S8 : vec3<f32>) -> Hit_0
{
    var hit_2 : Hit_0;
    hit_2.t_0 = 1.00000001504746622e+30f;
    hit_2.u_0 = 0.0f;
    hit_2.v_1 = 0.0f;
    hit_2.indexBase_1 = u32(0);
    hit_2.geomNodeIndex_1 = u32(0);
    hit_2.hit_0 = false;
    var stack_0 : array<u32, i32(32)>;
    var si_0 : u32 = u32(0);
    for(;;)
    {
        if(si_0 < u32(32))
        {
        }
        else
        {
            break;
        }
        stack_0[si_0] = u32(0);
        si_0 = si_0 + u32(1);
    }
    stack_0[u32(0)] = u32(0);
    var _S9 : vec3<f32> = vec3<f32>(1.0f) / _S8;
    var sp_0 : u32 = u32(1);
    for(;;)
    {
        if(sp_0 > u32(0))
        {
        }
        else
        {
            break;
        }
        var sp_1 : u32 = sp_0 - u32(1);
        var _S10 : BvhNode_std430_0 = bvhNodes_0[stack_0[sp_1]];
        if((intersectAabb_0(_S7, _S9, _S10.aabbMin_0, _S10.aabbMax_0, hit_2.t_0)) >= 1.00000001504746622e+30f)
        {
            sp_0 = sp_1;
            continue;
        }
        var _S11 : u32 = nodeLeftOrFirst_0(&(_S10));
        var _S12 : bool = nodeIsLeaf_0(&(_S10));
        var i_0 : u32;
        var sp_2 : u32;
        if(_S12)
        {
            var _S13 : u32 = nodeCountOrSecond_0(&(_S10));
            var _S14 : u32 = (_S13 & (u32(2147483647)));
            i_0 = u32(0);
            for(;;)
            {
                if(i_0 < _S14)
                {
                }
                else
                {
                    break;
                }
                var tr_0 : TriRef_std430_0 = triRefs_0[_S11 + i_0];
                var _S15 : Vertex_std430_0 = vertices_0[indices_0[triRefs_0[_S11 + i_0].indexBase_0]];
                var _S16 : Vertex_std430_0 = vertices_0[indices_0[triRefs_0[_S11 + i_0].indexBase_0 + u32(1)]];
                var _S17 : Vertex_std430_0 = vertices_0[indices_0[triRefs_0[_S11 + i_0].indexBase_0 + u32(2)]];
                var _S18 : vec3<f32> = vPos_0(&(_S15));
                var _S19 : vec3<f32> = vPos_0(&(_S16));
                var _S20 : vec3<f32> = vPos_0(&(_S17));
                var _S21 : bool = intersectTri_0(_S7, _S8, _S18, _S19, _S20, &(hit_2));
                if(_S21)
                {
                    hit_2.indexBase_1 = tr_0.indexBase_0;
                    hit_2.geomNodeIndex_1 = tr_0.geomNodeIndex_0;
                }
                i_0 = i_0 + u32(1);
            }
            sp_2 = sp_1;
        }
        else
        {
            var _S22 : u32 = nodeCountOrSecond_0(&(_S10));
            var tl_0 : f32 = intersectAabb_0(_S7, _S9, bvhNodes_0[_S11].aabbMin_0, bvhNodes_0[_S11].aabbMax_0, hit_2.t_0);
            var tr2_0 : f32 = intersectAabb_0(_S7, _S9, bvhNodes_0[_S22].aabbMin_0, bvhNodes_0[_S22].aabbMax_0, hit_2.t_0);
            var _S23 : bool = tl_0 <= tr2_0;
            if(_S23)
            {
                i_0 = _S11;
            }
            else
            {
                i_0 = _S22;
            }
            var far_0 : u32;
            if(_S23)
            {
                far_0 = _S22;
            }
            else
            {
                far_0 = _S11;
            }
            var _S24 : f32 = max(tl_0, tr2_0);
            var _S25 : f32 = min(tl_0, tr2_0);
            if((sp_1 + u32(2)) <= u32(32))
            {
                if(_S24 < 1.00000001504746622e+30f)
                {
                    var _S26 : u32 = sp_1 + u32(1);
                    stack_0[sp_1] = far_0;
                    sp_2 = _S26;
                }
                else
                {
                    sp_2 = sp_1;
                }
                var sp_3 : u32;
                if(_S25 < 1.00000001504746622e+30f)
                {
                    var _S27 : u32 = sp_2 + u32(1);
                    stack_0[sp_2] = i_0;
                    sp_3 = _S27;
                }
                else
                {
                    sp_3 = sp_2;
                }
                sp_2 = sp_3;
            }
            else
            {
                sp_2 = sp_1;
            }
        }
        sp_0 = sp_2;
    }
    return hit_2;
}

@compute
@workgroup_size(8, 8, 1)
fn computeMain(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var L_0 : vec3<f32>;
    var prev_0 : vec3<f32>;
    var w_1 : u32;
    var h_0 : u32;
    {var dim = textureDimensions((outImage_0));((w_1)) = dim.x;((h_0)) = dim.y;};
    var _S28 : u32 = tid_0.x;
    var _S29 : bool;
    if(_S28 >= w_1)
    {
        _S29 = true;
    }
    else
    {
        _S29 = (tid_0.y) >= h_0;
    }
    if(_S29)
    {
        return;
    }
    var _S30 : u32 = tid_0.y;
    var pix_0 : u32 = _S30 * w_1 + _S28;
    var sampleCount_0 : f32 = cam_0.control_0.x;
    var _S31 : u32 = u32(cam_0.control_0.y);
    var reset_0 : bool = (cam_0.control_0.z) > 0.5f;
    var seed_0 : u32 = ((((((_S28 * u32(1973)) ^ ((_S30 * u32(9277))))) ^ ((u32(sampleCount_0) * u32(26699))))) ^ (u32(2654435769)));
    var _S32 : f32 = rnd_0(&(seed_0));
    var _S33 : f32 = rnd_0(&(seed_0));
    var _S34 : vec2<u32> = tid_0.xy;
    var uv_0 : vec2<f32> = (vec2<f32>(_S34) + vec2<f32>(_S32, _S33)) / vec2<f32>(f32(w_1), f32(h_0));
    var _S35 : vec3<f32> = normalize(cam_0.camFwd_0.xyz + vec3<f32>((uv_0.x * 2.0f - 1.0f)) * cam_0.camRight_0.xyz + vec3<f32>((uv_0.y * 2.0f - 1.0f)) * cam_0.camUp_0.xyz);
    const _S36 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    const _S37 : vec3<f32> = vec3<f32>(1.0f, 1.0f, 1.0f);
    var ro_2 : vec3<f32> = cam_0.eye_0.xyz;
    var rd_1 : vec3<f32> = _S35;
    var bounce_0 : u32 = u32(0);
    var beta_0 : vec3<f32> = _S37;
    for(;;)
    {
        if(bounce_0 <= _S31)
        {
        }
        else
        {
            L_0 = _S36;
            break;
        }
        var _S38 : Hit_0 = traceBvh_0(ro_2, rd_1);
        if(!_S38.hit_0)
        {
            L_0 = beta_0 * skyColor_0(rd_1);
            break;
        }
        var gn_0 : GeometryNode_std430_0 = geometryNodes_0[_S38.geomNodeIndex_1];
        var _S39 : Vertex_std430_0 = vertices_0[indices_0[_S38.indexBase_1]];
        var _S40 : Vertex_std430_0 = vertices_0[indices_0[_S38.indexBase_1 + u32(1)]];
        var _S41 : Vertex_std430_0 = vertices_0[indices_0[_S38.indexBase_1 + u32(2)]];
        var _S42 : f32 = 1.0f - _S38.u_0 - _S38.v_1;
        var _S43 : vec3<f32> = vNormal_0(&(_S39));
        var _S44 : vec3<f32> = _S43 * vec3<f32>(_S42);
        var _S45 : vec3<f32> = vNormal_0(&(_S40));
        var _S46 : vec3<f32> = _S44 + _S45 * vec3<f32>(_S38.u_0);
        var _S47 : vec3<f32> = vNormal_0(&(_S41));
        var N_0 : vec3<f32> = normalize(_S46 + _S47 * vec3<f32>(_S38.v_1));
        var _S48 : vec2<f32> = vUv_0(&(_S39));
        var _S49 : vec2<f32> = _S48 * vec2<f32>(_S42);
        var _S50 : vec2<f32> = vUv_0(&(_S40));
        var _S51 : vec2<f32> = _S49 + _S50 * vec2<f32>(_S38.u_0);
        var _S52 : vec2<f32> = vUv_0(&(_S41));
        var texUv_0 : vec2<f32> = _S51 + _S52 * vec2<f32>(_S38.v_1);
        var P_0 : vec3<f32> = ro_2 + rd_1 * vec3<f32>(_S38.t_0);
        const _S53 : vec3<f32> = vec3<f32>(0.80000001192092896f, 0.80000001192092896f, 0.80000001192092896f);
        if((geometryNodes_0[_S38.geomNodeIndex_1].baseColorTexture_0) >= i32(0))
        {
            var _S54 : vec3<f32> = vec3<f32>(texUv_0, f32(gn_0.baseColorTexture_0));
            L_0 = (textureSampleLevel((textures_0), (samp_0), ((_S54)).xy, i32(((_S54)).z), (0.0f))).xyz;
        }
        else
        {
            L_0 = _S53;
        }
        if((dot(N_0, rd_1)) > 0.0f)
        {
            prev_0 = (vec3<f32>(0) - N_0);
        }
        else
        {
            prev_0 = N_0;
        }
        var beta_1 : vec3<f32> = beta_0 * L_0;
        if(bounce_0 >= u32(3))
        {
            var _S55 : f32 = max(beta_1.x, max(beta_1.y, beta_1.z));
            var _S56 : f32 = rnd_0(&(seed_0));
            if(_S56 > _S55)
            {
                L_0 = _S36;
                break;
            }
            beta_0 = beta_1 / vec3<f32>(max(_S55, 0.00009999999747379f));
        }
        else
        {
            beta_0 = beta_1;
        }
        var _S57 : vec3<f32> = P_0 + prev_0 * vec3<f32>(0.00100000004749745f);
        var _S58 : vec3<f32> = cosineSample_0(prev_0, &(seed_0));
        var bounce_1 : u32 = bounce_0 + u32(1);
        ro_2 = _S57;
        rd_1 = _S58;
        bounce_0 = bounce_1;
    }
    if(reset_0)
    {
        prev_0 = _S36;
    }
    else
    {
        prev_0 = accumBuffer_0[pix_0].xyz;
    }
    var acc_0 : vec3<f32> = prev_0 + L_0;
    accumBuffer_0[pix_0] = vec4<f32>(acc_0, 1.0f);
    var col_0 : vec3<f32> = acc_0 / vec3<f32>((sampleCount_0 + 1.0f));
    textureStore((outImage_0), (_S34), (vec4<f32>(pow(max(col_0 / (col_0 + vec3<f32>(1.0f)), vec3<f32>(0.0f)), vec3<f32>(0.45454543828964233f)), 1.0f)));
    return;
}


)VRIWGSL";
