#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_rtSoftwareWgsl[] = R"VRIWGSL(
@binding(1) @group(0) var outImage_0 : texture_storage_2d<rgba8unorm, write>;

struct Tri_std140_0
{
    @align(16) v0_0 : vec4<f32>,
    @align(16) v1_0 : vec4<f32>,
    @align(16) v2_0 : vec4<f32>,
    @align(16) nrm_0 : vec4<f32>,
    @align(16) albedo_0 : vec4<f32>,
};

struct _Array_std140_Tri64_0
{
    @align(16) data_0 : array<Tri_std140_0, i32(64)>,
};

struct Scene_std140_0
{
    @align(16) eye_0 : vec4<f32>,
    @align(16) camRight_0 : vec4<f32>,
    @align(16) camUp_0 : vec4<f32>,
    @align(16) camFwd_0 : vec4<f32>,
    @align(16) lightDir_0 : vec4<f32>,
    @align(16) params_0 : vec4<f32>,
    @align(16) tris_0 : _Array_std140_Tri64_0,
};

@binding(0) @group(0) var<uniform> g_0 : Scene_std140_0;
fn intersect_0( ro_0 : vec3<f32>,  rd_0 : vec3<f32>,  tri_0 : ptr<function, Tri_std140_0>,  t_0 : ptr<function, f32>) -> bool
{
    (*t_0) = 0.0f;
    var _S1 : vec3<f32> = (*tri_0).v0_0.xyz;
    var e1_0 : vec3<f32> = (*tri_0).v1_0.xyz - _S1;
    var e2_0 : vec3<f32> = (*tri_0).v2_0.xyz - _S1;
    var p_0 : vec3<f32> = cross(rd_0, e2_0);
    var det_0 : f32 = dot(e1_0, p_0);
    if((abs(det_0)) < 1.00000001168609742e-07f)
    {
        return false;
    }
    var inv_0 : f32 = 1.0f / det_0;
    var tv_0 : vec3<f32> = ro_0 - _S1;
    var u_0 : f32 = dot(tv_0, p_0) * inv_0;
    var _S2 : bool;
    if(u_0 < 0.0f)
    {
        _S2 = true;
    }
    else
    {
        _S2 = u_0 > 1.0f;
    }
    if(_S2)
    {
        return false;
    }
    var q_0 : vec3<f32> = cross(tv_0, e1_0);
    var v_0 : f32 = dot(rd_0, q_0) * inv_0;
    if(v_0 < 0.0f)
    {
        _S2 = true;
    }
    else
    {
        _S2 = (u_0 + v_0) > 1.0f;
    }
    if(_S2)
    {
        return false;
    }
    var _S3 : f32 = dot(e2_0, q_0) * inv_0;
    (*t_0) = _S3;
    return _S3 > 0.00100000004749745f;
}

fn intersect_1( ro_1 : vec3<f32>,  rd_1 : vec3<f32>,  tri_1 : ptr<function, Tri_std140_0>,  t_1 : ptr<function, f32>) -> bool
{
    (*t_1) = 0.0f;
    var _S4 : vec3<f32> = (*tri_1).v0_0.xyz;
    var e1_1 : vec3<f32> = (*tri_1).v1_0.xyz - _S4;
    var e2_1 : vec3<f32> = (*tri_1).v2_0.xyz - _S4;
    var p_1 : vec3<f32> = cross(rd_1, e2_1);
    var det_1 : f32 = dot(e1_1, p_1);
    if((abs(det_1)) < 1.00000001168609742e-07f)
    {
        return false;
    }
    var inv_1 : f32 = 1.0f / det_1;
    var tv_1 : vec3<f32> = ro_1 - _S4;
    var u_1 : f32 = dot(tv_1, p_1) * inv_1;
    var _S5 : bool;
    if(u_1 < 0.0f)
    {
        _S5 = true;
    }
    else
    {
        _S5 = u_1 > 1.0f;
    }
    if(_S5)
    {
        return false;
    }
    var q_1 : vec3<f32> = cross(tv_1, e1_1);
    var v_1 : f32 = dot(rd_1, q_1) * inv_1;
    if(v_1 < 0.0f)
    {
        _S5 = true;
    }
    else
    {
        _S5 = (u_1 + v_1) > 1.0f;
    }
    if(_S5)
    {
        return false;
    }
    var _S6 : f32 = dot(e2_1, q_1) * inv_1;
    (*t_1) = _S6;
    return _S6 > 0.00100000004749745f;
}

fn occluded_0( ro_2 : vec3<f32>,  rd_2 : vec3<f32>,  n_0 : i32) -> bool
{
    var i_0 : i32 = i32(0);
    for(;;)
    {
        if(i_0 < n_0)
        {
        }
        else
        {
            break;
        }
        var _S7 : Tri_std140_0 = g_0.tris_0.data_0[i_0];
        var t_2 : f32;
        var _S8 : bool = intersect_0(ro_2, rd_2, &(_S7), &(t_2));
        if(_S8)
        {
            return true;
        }
        i_0 = i_0 + i32(1);
    }
    return false;
}

@compute
@workgroup_size(8, 8, 1)
fn computeMain(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var w_0 : u32;
    var h_0 : u32;
    {var dim = textureDimensions((outImage_0));((w_0)) = dim.x;((h_0)) = dim.y;};
    var _S9 : bool;
    if((tid_0.x) >= w_0)
    {
        _S9 = true;
    }
    else
    {
        _S9 = (tid_0.y) >= h_0;
    }
    if(_S9)
    {
        return;
    }
    var _S10 : vec2<u32> = tid_0.xy;
    var uv_0 : vec2<f32> = (vec2<f32>(_S10) + vec2<f32>(0.5f)) / vec2<f32>(f32(w_0), f32(h_0));
    var ro_3 : vec3<f32> = g_0.eye_0.xyz;
    var rd_3 : vec3<f32> = normalize(g_0.camFwd_0.xyz + vec3<f32>((uv_0.x * 2.0f - 1.0f)) * g_0.camRight_0.xyz + vec3<f32>((1.0f - uv_0.y * 2.0f)) * g_0.camUp_0.xyz);
    var n_1 : i32 = i32(g_0.params_0.x);
    var ambient_0 : f32 = g_0.params_0.y;
    var bestT_0 : f32 = 1.00000001504746622e+30f;
    var hit_0 : i32 = i32(-1);
    var i_1 : i32 = i32(0);
    for(;;)
    {
        if(i_1 < n_1)
        {
        }
        else
        {
            break;
        }
        var _S11 : Tri_std140_0 = g_0.tris_0.data_0[i_1];
        var t_3 : f32;
        var _S12 : bool = intersect_1(ro_3, rd_3, &(_S11), &(t_3));
        if(_S12)
        {
            _S9 = t_3 < bestT_0;
        }
        else
        {
            _S9 = false;
        }
        if(_S9)
        {
            bestT_0 = t_3;
            hit_0 = i_1;
        }
        i_1 = i_1 + i32(1);
    }
    var color_0 : vec3<f32>;
    if(hit_0 < i32(0))
    {
        color_0 = mix(vec3<f32>(0.10000000149011612f, 0.11999999731779099f, 0.15999999642372131f), vec3<f32>(0.44999998807907104f, 0.62000000476837158f, 0.85000002384185791f), vec3<f32>(saturate(rd_3.y * 0.5f + 0.5f)));
    }
    else
    {
        var N_0 : vec3<f32> = normalize(g_0.tris_0.data_0[hit_0].nrm_0.xyz);
        var L_0 : vec3<f32> = normalize(g_0.lightDir_0.xyz);
        var shadow_0 : f32;
        if(occluded_0(ro_3 + rd_3 * vec3<f32>(bestT_0) + N_0 * vec3<f32>(0.0020000000949949f), L_0, n_1))
        {
            shadow_0 = 0.0f;
        }
        else
        {
            shadow_0 = 1.0f;
        }
        color_0 = g_0.tris_0.data_0[hit_0].albedo_0.xyz * vec3<f32>((ambient_0 + (1.0f - ambient_0) * max(dot(N_0, L_0), 0.0f) * shadow_0));
    }
    textureStore((outImage_0), (_S10), (vec4<f32>(color_0, 1.0f)));
    return;
}


)VRIWGSL";
