#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_showTexWgsl[] = R"VRIWGSL(
@binding(0) @group(0) var uTex_0 : texture_2d<f32>;

@binding(1) @group(0) var uSmp_0 : sampler;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var p_0 : vec2<f32> = vec2<f32>(f32((((vid_0 << (u32(1)))) & (u32(2)))), f32((vid_0 & (u32(2)))));
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_0 * vec2<f32>(2.0f) - vec2<f32>(1.0f), 0.0f, 1.0f);
    o_0.uv_0 = p_0;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
};

@fragment
fn fragmentMain( _S1 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S2 : pixelOutput_0 = pixelOutput_0( (textureSample((uTex_0), (uSmp_0), (_S1.uv_1))) );
    return _S2;
}


)VRIWGSL";
