#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_stencilOutlineWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Scene_std140_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightDir_0 : vec4<f32>,
    @align(16) outlineColor_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> u_0 : Scene_std140_0;
struct _MatrixStorage_float4x4std430_0
{
    @align(16) data_1 : array<vec4<f32>, i32(4)>,
};

struct Push_std430_0
{
    @align(16) model_0 : _MatrixStorage_float4x4std430_0,
};

var<uniform> pc_0 : Push_std430_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = ((((((vec4<f32>(_S1.position_1, 1.0f)) * (mat4x4<f32>(pc_0.model_0.data_1[i32(0)][i32(0)], pc_0.model_0.data_1[i32(0)][i32(1)], pc_0.model_0.data_1[i32(0)][i32(2)], pc_0.model_0.data_1[i32(0)][i32(3)], pc_0.model_0.data_1[i32(1)][i32(0)], pc_0.model_0.data_1[i32(1)][i32(1)], pc_0.model_0.data_1[i32(1)][i32(2)], pc_0.model_0.data_1[i32(1)][i32(3)], pc_0.model_0.data_1[i32(2)][i32(0)], pc_0.model_0.data_1[i32(2)][i32(1)], pc_0.model_0.data_1[i32(2)][i32(2)], pc_0.model_0.data_1[i32(2)][i32(3)], pc_0.model_0.data_1[i32(3)][i32(0)], pc_0.model_0.data_1[i32(3)][i32(1)], pc_0.model_0.data_1[i32(3)][i32(2)], pc_0.model_0.data_1[i32(3)][i32(3)]))))) * (mat4x4<f32>(u_0.viewProj_0.data_0[i32(0)][i32(0)], u_0.viewProj_0.data_0[i32(0)][i32(1)], u_0.viewProj_0.data_0[i32(0)][i32(2)], u_0.viewProj_0.data_0[i32(0)][i32(3)], u_0.viewProj_0.data_0[i32(1)][i32(0)], u_0.viewProj_0.data_0[i32(1)][i32(1)], u_0.viewProj_0.data_0[i32(1)][i32(2)], u_0.viewProj_0.data_0[i32(1)][i32(3)], u_0.viewProj_0.data_0[i32(2)][i32(0)], u_0.viewProj_0.data_0[i32(2)][i32(1)], u_0.viewProj_0.data_0[i32(2)][i32(2)], u_0.viewProj_0.data_0[i32(2)][i32(3)], u_0.viewProj_0.data_0[i32(3)][i32(0)], u_0.viewProj_0.data_0[i32(3)][i32(1)], u_0.viewProj_0.data_0[i32(3)][i32(2)], u_0.viewProj_0.data_0[i32(3)][i32(3)]))));
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

@fragment
fn fragmentMain(@builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var _S2 : pixelOutput_0 = pixelOutput_0( vec4<f32>(u_0.outlineColor_0.xyz, 1.0f) );
    return _S2;
}


)VRIWGSL";
