#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_triangleInstWgsl[] = R"VRIWGSL(
const kBase_0 : array<vec2<f32>, i32(3)> = array<vec2<f32>, i32(3)>( vec2<f32>(0.0f, -0.30000001192092896f), vec2<f32>(0.30000001192092896f, 0.30000001192092896f), vec2<f32>(-0.30000001192092896f, 0.30000001192092896f) );
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) color_0 : vec3<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32, @builtin(instance_index) iid_0 : u32) -> VSOutput_0
{
    var _S1 : bool = iid_0 == u32(0);
    var xoff_0 : f32;
    if(_S1)
    {
        xoff_0 = -0.40000000596046448f;
    }
    else
    {
        xoff_0 = 0.40000000596046448f;
    }
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(kBase_0[vid_0].x + xoff_0, kBase_0[vid_0].y, 0.0f, 1.0f);
    var _S2 : vec3<f32>;
    if(_S1)
    {
        _S2 = vec3<f32>(1.0f, 0.0f, 0.0f);
    }
    else
    {
        _S2 = vec3<f32>(0.0f, 1.0f, 0.0f);
    }
    o_0.color_0 = _S2;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) color_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S3 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S4 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S3.color_1, 1.0f) );
    return _S4;
}


)VRIWGSL";
