#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_triangleMrtWgsl[] = R"VRIWGSL(
const kPositions_0 : array<vec2<f32>, i32(3)> = array<vec2<f32>, i32(3)>( vec2<f32>(0.0f, -0.5f), vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, 0.5f) );
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(kPositions_0[vid_0], 0.0f, 1.0f);
    return o_0;
}

struct FSOutput_0
{
    @location(0) color0_0 : vec4<f32>,
    @location(1) color1_0 : vec4<f32>,
};

@fragment
fn fragmentMain() -> FSOutput_0
{
    var o_1 : FSOutput_0;
    o_1.color0_0 = vec4<f32>(1.0f, 0.0f, 0.0f, 1.0f);
    o_1.color1_0 = vec4<f32>(0.0f, 0.0f, 1.0f, 1.0f);
    return o_1;
}


)VRIWGSL";
