-- VRI examples. All web-capable: SDL3 windowing on desktop, the page canvas on wasm; the
-- shared host scaffolding lives in examples/common/example_app.h.
includes("triangle")
includes("cube")
includes("instancing")
includes("pbrbasic")
includes("pushconstants")
includes("normalmapping")
includes("computeshader")
includes("offscreen")
includes("descriptorindexing")
includes("shadowmapping")
includes("msaa")
includes("cubemap")
includes("stenciloutline")
