#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_compositeWgsl[] = R"VRIWGSL(
@binding(0) @group(0) var uAlbedo_0 : texture_2d<f32>;

@binding(2) @group(0) var uSmp_0 : sampler;

@binding(1) @group(0) var uNormal_0 : texture_2d<f32>;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) uv_0 : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var p_0 : vec2<f32> = vec2<f32>(f32((((vid_0 << (u32(1)))) & (u32(2)))), f32((vid_0 & (u32(2)))));
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(p_0 * vec2<f32>(2.0f) - vec2<f32>(1.0f), 0.0f, 1.0f);
    o_0.uv_0 = p_0;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) uv_1 : vec2<f32>,
};

@fragment
fn fragmentMain( _S1 : pixelInput_0, @builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S2 : f32 = _S1.uv_1.x;
    var _S3 : f32 = _S1.uv_1.y;
    var albedo_0 : vec4<f32> = (textureSample((uAlbedo_0), (uSmp_0), (vec2<f32>(_S2 * 2.0f, _S3))));
    var normal_0 : vec4<f32> = (textureSample((uNormal_0), (uSmp_0), (vec2<f32>((_S2 - 0.5f) * 2.0f, _S3))));
    var _S4 : vec4<f32>;
    if(_S2 < 0.5f)
    {
        _S4 = albedo_0;
    }
    else
    {
        _S4 = normal_0;
    }
    var _S5 : pixelOutput_0 = pixelOutput_0( _S4 );
    return _S5;
}


)VRIWGSL";
