#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_pushconstWgsl[] = R"VRIWGSL(
struct PushData_std430_0
{
    @align(16) color_0 : vec4<f32>,
};

var<uniform> pc_0 : PushData_std430_0;
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(vec2<f32>(f32((((vid_0 << (u32(1)))) & (u32(2)))), f32((vid_0 & (u32(2))))) * vec2<f32>(2.0f) - vec2<f32>(1.0f), 0.0f, 1.0f);
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

@fragment
fn fragmentMain(@builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S1 : pixelOutput_0 = pixelOutput_0( pc_0.color_0 );
    return _S1;
}


)VRIWGSL";
