#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_rtGltfSoftwareWgsl[] = R"VRIWGSL(
@binding(1) @group(0) var outImage_0 : texture_storage_2d<rgba8unorm, write>;

struct Camera_std140_0
{
    @align(16) eye_0 : vec4<f32>,
    @align(16) camRight_0 : vec4<f32>,
    @align(16) camUp_0 : vec4<f32>,
    @align(16) camFwd_0 : vec4<f32>,
    @align(16) lightDir_0 : vec4<f32>,
    @align(16) params_0 : vec4<f32>,
};

@binding(2) @group(0) var<uniform> cam_0 : Camera_std140_0;
struct Vertex_std430_0
{
    @align(16) a_0 : vec4<f32>,
    @align(16) b_0 : vec4<f32>,
};

@binding(3) @group(0) var<storage, read_write> vertices_0 : array<Vertex_std430_0>;

@binding(4) @group(0) var<storage, read_write> indices_0 : array<u32>;

struct BvhNode_std430_0
{
    @align(16) aabbMin_0 : vec3<f32>,
    @align(4) leftOrFirst_0 : u32,
    @align(16) aabbMax_0 : vec3<f32>,
    @align(4) countOrSecond_0 : u32,
};

@binding(8) @group(0) var<storage, read_write> bvhNodes_0 : array<BvhNode_std430_0>;

struct TriRef_std430_0
{
    @align(4) indexBase_0 : u32,
    @align(4) geomNodeIndex_0 : u32,
};

@binding(9) @group(0) var<storage, read_write> triRefs_0 : array<TriRef_std430_0>;

struct GeometryNode_std430_0
{
    @align(4) firstIndex_0 : u32,
    @align(4) baseColorTexture_0 : i32,
    @align(4) occlusionTexture_0 : i32,
    @align(4) _pad_0 : u32,
};

@binding(5) @group(0) var<storage, read_write> geometryNodes_0 : array<GeometryNode_std430_0>;

@binding(7) @group(0) var textures_0 : texture_2d_array<f32>;

@binding(6) @group(0) var samp_0 : sampler;

fn intersectAabb_0( ro_0 : vec3<f32>,  invRd_0 : vec3<f32>,  bmin_0 : vec3<f32>,  bmax_0 : vec3<f32>,  tMax_0 : f32) -> f32
{
    var t0_0 : vec3<f32> = (bmin_0 - ro_0) * invRd_0;
    var t1_0 : vec3<f32> = (bmax_0 - ro_0) * invRd_0;
    var mn_0 : vec3<f32> = min(t0_0, t1_0);
    var mx_0 : vec3<f32> = max(t0_0, t1_0);
    var _S1 : f32 = max(max(mn_0.x, mn_0.y), max(mn_0.z, 0.0f));
    var _S2 : f32;
    if((min(min(mx_0.x, mx_0.y), min(mx_0.z, tMax_0))) >= _S1)
    {
        _S2 = _S1;
    }
    else
    {
        _S2 = 1.00000001504746622e+30f;
    }
    return _S2;
}

fn nodeLeftOrFirst_0( n_0 : ptr<function, BvhNode_std430_0>) -> u32
{
    return (*n_0).leftOrFirst_0;
}

fn nodeIsLeaf_0( n_1 : ptr<function, BvhNode_std430_0>) -> bool
{
    return ((((*n_1).countOrSecond_0) & (u32(2147483648)))) != u32(0);
}

fn nodeCountOrSecond_0( n_2 : ptr<function, BvhNode_std430_0>) -> u32
{
    return (*n_2).countOrSecond_0;
}

fn vPos_0( v_0 : ptr<function, Vertex_std430_0>) -> vec3<f32>
{
    return (*v_0).a_0.xyz;
}

struct Hit_0
{
     t_0 : f32,
     u_0 : f32,
     v_1 : f32,
     indexBase_1 : u32,
     geomNodeIndex_1 : u32,
     hit_0 : bool,
};

fn intersectTri_0( ro_1 : vec3<f32>,  rd_0 : vec3<f32>,  p0_0 : vec3<f32>,  p1_0 : vec3<f32>,  p2_0 : vec3<f32>,  hit_1 : ptr<function, Hit_0>) -> bool
{
    var e1_0 : vec3<f32> = p1_0 - p0_0;
    var e2_0 : vec3<f32> = p2_0 - p0_0;
    var p_0 : vec3<f32> = cross(rd_0, e2_0);
    var det_0 : f32 = dot(e1_0, p_0);
    if((abs(det_0)) < 1.00000001168609742e-07f)
    {
        return false;
    }
    var invDet_0 : f32 = 1.0f / det_0;
    var tv_0 : vec3<f32> = ro_1 - p0_0;
    var u_1 : f32 = dot(tv_0, p_0) * invDet_0;
    var _S3 : bool;
    if(u_1 < 0.0f)
    {
        _S3 = true;
    }
    else
    {
        _S3 = u_1 > 1.0f;
    }
    if(_S3)
    {
        return false;
    }
    var q_0 : vec3<f32> = cross(tv_0, e1_0);
    var v_2 : f32 = dot(rd_0, q_0) * invDet_0;
    if(v_2 < 0.0f)
    {
        _S3 = true;
    }
    else
    {
        _S3 = (u_1 + v_2) > 1.0f;
    }
    if(_S3)
    {
        return false;
    }
    var t_1 : f32 = dot(e2_0, q_0) * invDet_0;
    if(t_1 <= 0.00100000004749745f)
    {
        _S3 = true;
    }
    else
    {
        _S3 = t_1 >= ((*hit_1).t_0);
    }
    if(_S3)
    {
        return false;
    }
    (*hit_1).t_0 = t_1;
    (*hit_1).u_0 = u_1;
    (*hit_1).v_1 = v_2;
    (*hit_1).hit_0 = true;
    return true;
}

fn vNormal_0( v_3 : ptr<function, Vertex_std430_0>) -> vec3<f32>
{
    return vec3<f32>((*v_3).a_0.w, (*v_3).b_0.x, (*v_3).b_0.y);
}

fn vUv_0( v_4 : ptr<function, Vertex_std430_0>) -> vec2<f32>
{
    return (*v_4).b_0.zw;
}

fn traceBvh_0( _S4 : vec3<f32>,  _S5 : vec3<f32>) -> Hit_0
{
    var hit_2 : Hit_0;
    hit_2.t_0 = 1.00000001504746622e+30f;
    hit_2.u_0 = 0.0f;
    hit_2.v_1 = 0.0f;
    hit_2.indexBase_1 = u32(0);
    hit_2.geomNodeIndex_1 = u32(0);
    hit_2.hit_0 = false;
    var stack_0 : array<u32, i32(32)>;
    var si_0 : u32 = u32(0);
    for(;;)
    {
        if(si_0 < u32(32))
        {
        }
        else
        {
            break;
        }
        stack_0[si_0] = u32(0);
        si_0 = si_0 + u32(1);
    }
    stack_0[u32(0)] = u32(0);
    var _S6 : vec3<f32> = vec3<f32>(1.0f) / _S5;
    var sp_0 : u32 = u32(1);
    for(;;)
    {
        if(sp_0 > u32(0))
        {
        }
        else
        {
            break;
        }
        var sp_1 : u32 = sp_0 - u32(1);
        var _S7 : BvhNode_std430_0 = bvhNodes_0[stack_0[sp_1]];
        if((intersectAabb_0(_S4, _S6, _S7.aabbMin_0, _S7.aabbMax_0, hit_2.t_0)) >= 1.00000001504746622e+30f)
        {
            sp_0 = sp_1;
            continue;
        }
        var _S8 : u32 = nodeLeftOrFirst_0(&(_S7));
        var _S9 : bool = nodeIsLeaf_0(&(_S7));
        var i_0 : u32;
        var sp_2 : u32;
        if(_S9)
        {
            var _S10 : u32 = nodeCountOrSecond_0(&(_S7));
            var _S11 : u32 = (_S10 & (u32(2147483647)));
            i_0 = u32(0);
            for(;;)
            {
                if(i_0 < _S11)
                {
                }
                else
                {
                    break;
                }
                var tr_0 : TriRef_std430_0 = triRefs_0[_S8 + i_0];
                var _S12 : Vertex_std430_0 = vertices_0[indices_0[triRefs_0[_S8 + i_0].indexBase_0]];
                var _S13 : Vertex_std430_0 = vertices_0[indices_0[triRefs_0[_S8 + i_0].indexBase_0 + u32(1)]];
                var _S14 : Vertex_std430_0 = vertices_0[indices_0[triRefs_0[_S8 + i_0].indexBase_0 + u32(2)]];
                var _S15 : vec3<f32> = vPos_0(&(_S12));
                var _S16 : vec3<f32> = vPos_0(&(_S13));
                var _S17 : vec3<f32> = vPos_0(&(_S14));
                var _S18 : bool = intersectTri_0(_S4, _S5, _S15, _S16, _S17, &(hit_2));
                if(_S18)
                {
                    hit_2.indexBase_1 = tr_0.indexBase_0;
                    hit_2.geomNodeIndex_1 = tr_0.geomNodeIndex_0;
                }
                i_0 = i_0 + u32(1);
            }
            sp_2 = sp_1;
        }
        else
        {
            var _S19 : u32 = nodeCountOrSecond_0(&(_S7));
            var tl_0 : f32 = intersectAabb_0(_S4, _S6, bvhNodes_0[_S8].aabbMin_0, bvhNodes_0[_S8].aabbMax_0, hit_2.t_0);
            var tr2_0 : f32 = intersectAabb_0(_S4, _S6, bvhNodes_0[_S19].aabbMin_0, bvhNodes_0[_S19].aabbMax_0, hit_2.t_0);
            var _S20 : bool = tl_0 <= tr2_0;
            if(_S20)
            {
                i_0 = _S8;
            }
            else
            {
                i_0 = _S19;
            }
            var far_0 : u32;
            if(_S20)
            {
                far_0 = _S19;
            }
            else
            {
                far_0 = _S8;
            }
            var _S21 : f32 = max(tl_0, tr2_0);
            var _S22 : f32 = min(tl_0, tr2_0);
            if((sp_1 + u32(2)) <= u32(32))
            {
                if(_S21 < 1.00000001504746622e+30f)
                {
                    var _S23 : u32 = sp_1 + u32(1);
                    stack_0[sp_1] = far_0;
                    sp_2 = _S23;
                }
                else
                {
                    sp_2 = sp_1;
                }
                var sp_3 : u32;
                if(_S22 < 1.00000001504746622e+30f)
                {
                    var _S24 : u32 = sp_2 + u32(1);
                    stack_0[sp_2] = i_0;
                    sp_3 = _S24;
                }
                else
                {
                    sp_3 = sp_2;
                }
                sp_2 = sp_3;
            }
            else
            {
                sp_2 = sp_1;
            }
        }
        sp_0 = sp_2;
    }
    return hit_2;
}

fn traceShade_0( ndc_0 : vec2<f32>) -> vec3<f32>
{
    var _S25 : Hit_0 = traceBvh_0(cam_0.eye_0.xyz, normalize(cam_0.camFwd_0.xyz + vec3<f32>(ndc_0.x) * cam_0.camRight_0.xyz + vec3<f32>(ndc_0.y) * cam_0.camUp_0.xyz));
    if(!_S25.hit_0)
    {
        return vec3<f32>(0.12999999523162842f, 0.15999999642372131f, 0.2199999988079071f);
    }
    var gn_0 : GeometryNode_std430_0 = geometryNodes_0[_S25.geomNodeIndex_1];
    var _S26 : Vertex_std430_0 = vertices_0[indices_0[_S25.indexBase_1]];
    var _S27 : Vertex_std430_0 = vertices_0[indices_0[_S25.indexBase_1 + u32(1)]];
    var _S28 : Vertex_std430_0 = vertices_0[indices_0[_S25.indexBase_1 + u32(2)]];
    var _S29 : f32 = 1.0f - _S25.u_0 - _S25.v_1;
    var _S30 : vec3<f32> = vNormal_0(&(_S26));
    var _S31 : vec3<f32> = _S30 * vec3<f32>(_S29);
    var _S32 : vec3<f32> = vNormal_0(&(_S27));
    var _S33 : vec3<f32> = _S31 + _S32 * vec3<f32>(_S25.u_0);
    var _S34 : vec3<f32> = vNormal_0(&(_S28));
    var N_0 : vec3<f32> = normalize(_S33 + _S34 * vec3<f32>(_S25.v_1));
    var _S35 : vec2<f32> = vUv_0(&(_S26));
    var _S36 : vec2<f32> = _S35 * vec2<f32>(_S29);
    var _S37 : vec2<f32> = vUv_0(&(_S27));
    var _S38 : vec2<f32> = _S36 + _S37 * vec2<f32>(_S25.u_0);
    var _S39 : vec2<f32> = vUv_0(&(_S28));
    var texUv_0 : vec2<f32> = _S38 + _S39 * vec2<f32>(_S25.v_1);
    const _S40 : vec3<f32> = vec3<f32>(0.80000001192092896f, 0.80000001192092896f, 0.80000001192092896f);
    var albedo_0 : vec3<f32>;
    if((geometryNodes_0[_S25.geomNodeIndex_1].baseColorTexture_0) >= i32(0))
    {
        var _S41 : vec3<f32> = vec3<f32>(texUv_0, f32(gn_0.baseColorTexture_0));
        albedo_0 = (textureSampleLevel((textures_0), (samp_0), ((_S41)).xy, i32(((_S41)).z), (0.0f))).xyz;
    }
    else
    {
        albedo_0 = _S40;
    }
    if((gn_0.occlusionTexture_0) >= i32(0))
    {
        var _S42 : vec3<f32> = vec3<f32>(texUv_0, f32(gn_0.occlusionTexture_0));
        albedo_0 = albedo_0 * vec3<f32>((textureSampleLevel((textures_0), (samp_0), ((_S42)).xy, i32(((_S42)).z), (0.0f))).x);
    }
    else
    {
    }
    return albedo_0 * (mix(vec3<f32>(0.2199999988079071f, 0.23999999463558197f, 0.30000001192092896f), vec3<f32>(0.68000000715255737f, 0.72000002861022949f, 0.80000001192092896f), vec3<f32>((0.5f + 0.5f * N_0.y))) * vec3<f32>((cam_0.params_0.x * 2.5f)) + vec3<f32>(max(dot(N_0, normalize(cam_0.lightDir_0.xyz)), 0.0f)));
}

@compute
@workgroup_size(8, 8, 1)
fn computeMain(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var w_0 : u32;
    var h_0 : u32;
    {var dim = textureDimensions((outImage_0));((w_0)) = dim.x;((h_0)) = dim.y;};
    var _S43 : bool;
    if((tid_0.x) >= w_0)
    {
        _S43 = true;
    }
    else
    {
        _S43 = (tid_0.y) >= h_0;
    }
    if(_S43)
    {
        return;
    }
    var _S44 : array<vec2<f32>, i32(4)> = array<vec2<f32>, i32(4)>( vec2<f32>(-0.125f, -0.375f), vec2<f32>(0.375f, -0.125f), vec2<f32>(0.125f, 0.375f), vec2<f32>(-0.375f, 0.125f) );
    const _S45 : vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var s_0 : i32 = i32(0);
    var color_0 : vec3<f32> = _S45;
    for(;;)
    {
        if(s_0 < i32(4))
        {
        }
        else
        {
            break;
        }
        var uv_0 : vec2<f32> = (vec2<f32>(tid_0.xy) + vec2<f32>(0.5f) + _S44[s_0]) / vec2<f32>(f32(w_0), f32(h_0));
        var color_1 : vec3<f32> = color_0 + traceShade_0(vec2<f32>(uv_0.x * 2.0f - 1.0f, uv_0.y * 2.0f - 1.0f));
        s_0 = s_0 + i32(1);
        color_0 = color_1;
    }
    textureStore((outImage_0), (tid_0.xy), (vec4<f32>(color_0 * vec3<f32>(0.25f), 1.0f)));
    return;
}


)VRIWGSL";
