#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_shadowDepthWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Scene_std140_0
{
    @align(16) camViewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightViewProj_0 : _MatrixStorage_float4x4std140_0,
    @align(16) lightDir_0 : vec4<f32>,
    @align(16) params_0 : vec4<f32>,
};

@binding(0) @group(0) var<uniform> u_0 : Scene_std140_0;
struct _MatrixStorage_float4x4std430_0
{
    @align(16) data_1 : array<vec4<f32>, i32(4)>,
};

struct Push_std430_0
{
    @align(16) model_0 : _MatrixStorage_float4x4std430_0,
};

var<uniform> pc_0 : Push_std430_0;
struct vertexOutput_0
{
    @builtin(position) output_0 : vec4<f32>,
};

struct vertexInput_0
{
    @location(0) position_0 : vec3<f32>,
    @location(1) normal_0 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> vertexOutput_0
{
    var _S2 : vertexOutput_0 = vertexOutput_0( ((((((vec4<f32>(_S1.position_0, 1.0f)) * (mat4x4<f32>(pc_0.model_0.data_1[i32(0)][i32(0)], pc_0.model_0.data_1[i32(0)][i32(1)], pc_0.model_0.data_1[i32(0)][i32(2)], pc_0.model_0.data_1[i32(0)][i32(3)], pc_0.model_0.data_1[i32(1)][i32(0)], pc_0.model_0.data_1[i32(1)][i32(1)], pc_0.model_0.data_1[i32(1)][i32(2)], pc_0.model_0.data_1[i32(1)][i32(3)], pc_0.model_0.data_1[i32(2)][i32(0)], pc_0.model_0.data_1[i32(2)][i32(1)], pc_0.model_0.data_1[i32(2)][i32(2)], pc_0.model_0.data_1[i32(2)][i32(3)], pc_0.model_0.data_1[i32(3)][i32(0)], pc_0.model_0.data_1[i32(3)][i32(1)], pc_0.model_0.data_1[i32(3)][i32(2)], pc_0.model_0.data_1[i32(3)][i32(3)]))))) * (mat4x4<f32>(u_0.lightViewProj_0.data_0[i32(0)][i32(0)], u_0.lightViewProj_0.data_0[i32(0)][i32(1)], u_0.lightViewProj_0.data_0[i32(0)][i32(2)], u_0.lightViewProj_0.data_0[i32(0)][i32(3)], u_0.lightViewProj_0.data_0[i32(1)][i32(0)], u_0.lightViewProj_0.data_0[i32(1)][i32(1)], u_0.lightViewProj_0.data_0[i32(1)][i32(2)], u_0.lightViewProj_0.data_0[i32(1)][i32(3)], u_0.lightViewProj_0.data_0[i32(2)][i32(0)], u_0.lightViewProj_0.data_0[i32(2)][i32(1)], u_0.lightViewProj_0.data_0[i32(2)][i32(2)], u_0.lightViewProj_0.data_0[i32(2)][i32(3)], u_0.lightViewProj_0.data_0[i32(3)][i32(0)], u_0.lightViewProj_0.data_0[i32(3)][i32(1)], u_0.lightViewProj_0.data_0[i32(3)][i32(2)], u_0.lightViewProj_0.data_0[i32(3)][i32(3)])))) );
    return _S2;
}

@fragment
fn fragmentMain()
{
    return;
}


)VRIWGSL";
