#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_skyboxWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4std140_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Scene_std140_0
{
    @align(16) viewProj_0 : _MatrixStorage_float4x4std140_0,
};

@binding(0) @group(0) var<uniform> u_0 : Scene_std140_0;
@binding(1) @group(0) var sky_0 : texture_cube<f32>;

@binding(2) @group(0) var smp_0 : sampler;

struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) dir_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(_S1.position_1, 1.0f)) * (mat4x4<f32>(u_0.viewProj_0.data_0[i32(0)][i32(0)], u_0.viewProj_0.data_0[i32(0)][i32(1)], u_0.viewProj_0.data_0[i32(0)][i32(2)], u_0.viewProj_0.data_0[i32(0)][i32(3)], u_0.viewProj_0.data_0[i32(1)][i32(0)], u_0.viewProj_0.data_0[i32(1)][i32(1)], u_0.viewProj_0.data_0[i32(1)][i32(2)], u_0.viewProj_0.data_0[i32(1)][i32(3)], u_0.viewProj_0.data_0[i32(2)][i32(0)], u_0.viewProj_0.data_0[i32(2)][i32(1)], u_0.viewProj_0.data_0[i32(2)][i32(2)], u_0.viewProj_0.data_0[i32(2)][i32(3)], u_0.viewProj_0.data_0[i32(3)][i32(0)], u_0.viewProj_0.data_0[i32(3)][i32(1)], u_0.viewProj_0.data_0[i32(3)][i32(2)], u_0.viewProj_0.data_0[i32(3)][i32(3)]))));
    o_0.dir_0 = _S1.position_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) dir_1 : vec3<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var _S3 : pixelOutput_0 = pixelOutput_0( (textureSample((sky_0), (smp_0), (normalize(_S2.dir_1)))) );
    return _S3;
}


)VRIWGSL";
