#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_triangleVbufWgsl[] = R"VRIWGSL(
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
    @location(0) color_0 : vec3<f32>,
};

struct vertexInput_0
{
    @location(0) position_1 : vec3<f32>,
    @location(1) color_1 : vec3<f32>,
};

@vertex
fn vertexMain( _S1 : vertexInput_0) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = vec4<f32>(_S1.position_1, 1.0f);
    o_0.color_0 = _S1.color_1;
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

struct pixelInput_0
{
    @location(0) color_2 : vec3<f32>,
};

@fragment
fn fragmentMain( _S2 : pixelInput_0, @builtin(position) position_2 : vec4<f32>) -> pixelOutput_0
{
    var _S3 : pixelOutput_0 = pixelOutput_0( vec4<f32>(_S2.color_2, 1.0f) );
    return _S3;
}


)VRIWGSL";
