#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_trianglePushWgsl[] = R"VRIWGSL(
struct _MatrixStorage_float4x4_ColMajorstd430_0
{
    @align(16) data_0 : array<vec4<f32>, i32(4)>,
};

struct Push_std430_0
{
    @align(16) mvp_0 : _MatrixStorage_float4x4_ColMajorstd430_0,
};

var<uniform> pc_0 : Push_std430_0;
const kPositions_0 : array<vec2<f32>, i32(3)> = array<vec2<f32>, i32(3)>( vec2<f32>(0.0f, -0.5f), vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, 0.5f) );
struct VSOutput_0
{
    @builtin(position) position_0 : vec4<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) vid_0 : u32) -> VSOutput_0
{
    var o_0 : VSOutput_0;
    o_0.position_0 = (((vec4<f32>(kPositions_0[vid_0], 0.0f, 1.0f)) * (mat4x4<f32>(mat4x4<f32>(pc_0.mvp_0.data_0[i32(0)][i32(0)], pc_0.mvp_0.data_0[i32(1)][i32(0)], pc_0.mvp_0.data_0[i32(2)][i32(0)], pc_0.mvp_0.data_0[i32(3)][i32(0)], pc_0.mvp_0.data_0[i32(0)][i32(1)], pc_0.mvp_0.data_0[i32(1)][i32(1)], pc_0.mvp_0.data_0[i32(2)][i32(1)], pc_0.mvp_0.data_0[i32(3)][i32(1)], pc_0.mvp_0.data_0[i32(0)][i32(2)], pc_0.mvp_0.data_0[i32(1)][i32(2)], pc_0.mvp_0.data_0[i32(2)][i32(2)], pc_0.mvp_0.data_0[i32(3)][i32(2)], pc_0.mvp_0.data_0[i32(0)][i32(3)], pc_0.mvp_0.data_0[i32(1)][i32(3)], pc_0.mvp_0.data_0[i32(2)][i32(3)], pc_0.mvp_0.data_0[i32(3)][i32(3)])))));
    return o_0;
}

struct pixelOutput_0
{
    @location(0) output_0 : vec4<f32>,
};

@fragment
fn fragmentMain(@builtin(position) position_1 : vec4<f32>) -> pixelOutput_0
{
    var _S1 : pixelOutput_0 = pixelOutput_0( vec4<f32>(0.0f, 1.0f, 0.0f, 1.0f) );
    return _S1;
}


)VRIWGSL";
