#pragma once
// Generated by vri-shaderc (Slang -> WGSL). Do not edit by hand.
inline const char g_waveWgsl[] = R"VRIWGSL(
enable subgroups;
@binding(0) @group(0) var<storage, read_write> outBuf_0 : array<u32>;

@compute
@workgroup_size(64, 1, 1)
fn computeMain(@builtin(global_invocation_id) tid_0 : vec3<u32>)
{
    var _S1 : u32 = subgroupAdd(u32(1));
    outBuf_0[tid_0.x] = _S1;
    return;
}


)VRIWGSL";
